### ISSUE TITLE
Less power consumption report 

### ISSUE THREAD

**Issue by justme871** [azerty9971/xtend_tuya#187]
Is not grabbing the correct daily, monthly or yearly consumption. Every time are less kw. Also the report sometimes need more than one hour to be updated. 
Used 2 smart breaker Earu EAKCB--M. 

![Screenshot_20250103_143525_Home Assistant](https://github.com/user-attachments/assets/c19b39ea-2307-4060-b9cb-86f8d49ee4c1)
![Screenshot_20250103_143506_Tuya Smart](https://github.com/user-attachments/assets/6deb4891-047b-4023-b095-34afc584bc67)

**Comment by justme871** [comment]
Last 2 days on HA it was reported doubled consumption....




![Screenshot_20250107_181109_WhatsApp](https://github.com/user-attachments/assets/001a15e5-d07a-4106-9e25-3b44546f9e46)
![Screenshot_20250107_181102_WhatsApp](https://github.com/user-attachments/assets/e9450ad6-24b5-4183-8535-432e9145248e)
![Screenshot_20250107_180930_Home Assistant](https://github.com/user-attachments/assets/e037ab3d-9307-444f-879e-9f90bef6ab33)
![Screenshot_20250107_180948_Tuya Smart](https://github.com/user-attachments/assets/841b27b2-4074-4648-8ef8-9bcab6850ebb)

**Comment by justme871** [comment]
Hi

Thank you

**Comment by spideraxal** [comment]
Hi @azerty9971 ! 

Any time-frame for the next release?

**Comment by azerty9971** [comment]
Hello,
Can you retry with 3.0.8-beta.1?

It should fix the issue :).

Have a nice day,
Azerty

**Comment by spideraxal** [comment]
I tried with v3.0.8-beta.4, but it is still reporting less power consumption than the app.

<img width="566" alt="Image" src="https://github.com/user-attachments/assets/ef0890ef-0b70-4c08-a886-cc9fc1045b9b" />

<img width="422" alt="Image" src="https://github.com/user-attachments/assets/32166d46-9615-4d48-ac61-3dc842536e65" />

**Comment by azerty9971** [comment]
That is normal, the monthly consumption will start to be correct as from Feb 1st...
Can you compare the hourly values in the energy dashboard with the reporting you have in the Tuya App?

These should now match :).

The way this works is that the cloud send each time the consumption from the last time it sent a consumption (so the delta).
If some messages are missed then they don't appear in HA (which was the case with the current release), hope it's more clear this way :).

Have a nice day,
Azerty

**Comment by spideraxal** [comment]
I can't compare the hourly ones, I don't have that option. I'll check the daily usage tomorrow, based on your changes, that should be the same as in the Tuya app.

Anyway, thanks for the awesome integration!

**Comment by egaldg** [comment]
Thanks for your response, i will retry it later, we are going on a holiday...
After copying the beta 5 i see all my devices double in Xtend_Tuya by the way...

Grtz Egaldg

**Comment by azerty9971** [comment]
> Thanks for your response, i will retry it later, we are going on a holiday... After copying the beta 5 i see all my devices double in Xtend_Tuya by the way...
> 
> Grtz Egaldg

I've seen this happen, just restart HA and it should be fixed :).

Have a nice day,
Azerty

**Comment by egaldg** [comment]
allready restarted HA a few times now, also cut the power for a while, still double devices...

**Comment by spideraxal** [comment]
In my case, the integration displays the same power consumption in HA as in Smart Life (for the current day/month).

The issue might be related to your setup @egaldg

**Comment by egaldg** [comment]
I still have to check the power consumption, it might be ok now, but i still have all my devices twice in XTendTuya.
The are not double in IOT.Tuya or my smartlife app, only in XTend Tuya

**Comment by justme871** [comment]
> I still have to check the power consumption, it might be ok now, but i still have all my devices twice in XTendTuya. The are not double in IOT.Tuya or my smartlife app, only in XTend Tuya


Now I get same problem. The metering is not displayed on HA. Do you find the issue?

**Comment by egaldg** [comment]
Hi, back home now. No i don't use multiple accounts or shared devices. To be sure i uninstalled Tuya.local but still the same, all devices are shown twice (scenes not). There is every time one that says unsupported and one normal... The unsupported have also entities but less. I don't use official Tuya.

![Image](https://github.com/user-attachments/assets/6b58fb2b-e511-400c-afb2-c0ab3887332d)

**Comment by egaldg** [comment]
Hi, i removed all my devices in the smartlife app en re-added them. Now everything is OK... Consumption also looks OK now. Thanks !

**Comment by azerty9971** [comment]
Happy to know that it worked for you!!

Have a nice day!
Azerty
