### ISSUE TITLE
problems after HA update 2025.3

### ISSUE THREAD

**Issue by egaldg** [azerty9971/xtend_tuya#224]
Yesterday i updated HA to 2025.3 and today i noticed that after that it my devices were not switched this morning by the automation.
Also switching the devices on and off in HA did not work well, sometimes they switched on but i could not switch them off anymore. Sync or connection seemed disturbed. 
In smartlife app all went well...
I restored my HA backup that was made just before the update and all seems to be OK again (after reconnecting XtendTuya to the smartlife app because it asked so after the backup restore).

Anyone else experiencing problems after 2025.3 update ?

Grtz Egaldg

**Comment by maxisamu** [comment]
I have exactly the same issue! 
Lights can be turned ON, but not OFF through the dashboard. The only way to switch them OFF is to go to the entity and switch them OFF there.
The PIR sensors do not work at all.
I also went back two days with my backup and everything is working well. When I then upgrade to HA 2025.3 the same issues appear.
All other integrations are not affected, so this must be an issue with "xtend tuya".

I was already considering going to the [official Tuya integration](https://www.home-assistant.io/integrations/tuya/), but hope there is a fix to maintain the "xtend" version.

**Comment by maxisamu** [comment]
BTW: if I switch to the [official Tuya integration](https://www.home-assistant.io/integrations/tuya/), is there a way to maintain my entities, hence automations and scripts, or will I need to re-do this migration manually myself?

**Comment by italo-lombardi** [comment]
> BTW: if I switch to the [official Tuya integration](https://www.home-assistant.io/integrations/tuya/), is there a way to maintain my entities, hence automations and scripts, or will I need to re-do this migration manually myself?

My previous setup: xtend_tuya + official tuya. 
I disabled extend_tuya, and all devices are functioning properly. However, Tuya scenes received new IDs with a "_2" suffix, breaking all automations and scripts that rely on them.

It might happen to you the same if you have a similar setup. 

If you don't have this setup, maybe it's better first to add official tuya integration and then disable xtend_tuya (or wait for a fix here)

**Comment by andreaskoelsch** [comment]
I'm using Xtend Tuya in combination with local tuya. The only thing I use Xtend Tuya for is the daily, monthly, ... Consumption values and those are broken now. Will roll back to a backup and follow this issue to wait for a fix.

**Comment by Tazrd** [comment]
I can confirm that I am having similar issues to above whilst using 2025.3.

**Comment by Leons77** [comment]
I can confirm that I have it anyway

**Comment by azerty9971** [comment]
Hello,
The latest stable release should fix this issue :)

Let me know if you still encounter issues.

Have a nice day,
Azerty

**Comment by andreaskoelsch** [comment]
Looks like it's working from my side. However, now my plug is listed twice. The one with history and all shows unsupported. The second one has all entities with _2 suffix. How can I fix that so that the update keeps using the old entities?

**Comment by egaldg** [comment]
Hi, after updating XT all my devices in XT are gone... reloading does not help...

**Comment by egaldg** [comment]
I also allready removed hub and readded through rebounding with qr code but still no devices... Tuya Iot shows all devices OK.

**Comment by egaldg** [comment]
After deleting XT and redownloading the beta 5 version devices are back

**Comment by egaldg** [comment]
But it seems all my devices  have another device-id now and all automations are broken :-(((

**Comment by Leons77** [comment]
my devices have another device-id now

**Comment by egaldg** [comment]
for me too, restoring HA backup from before updating fixed it for me

**Comment by azerty9971** [comment]
Hello regarding the duplicated entities, can you try restarting HA 2 times after updating?

And for those that don't have any devices recognized, can you look in "Settings -> System -> Logs" and let me know if you have an error?

Thanks in advance,
Azerty

**Comment by andreaskoelsch** [comment]
I did restart twice, but the double entries are still there. Could it be because I already disabled the stale device and started renaming some of the entities so my automations work?

**Comment by philspain72** [comment]
Same no Energy readings in the Energy Dashboard now its created a new sensor with 2 on the end, but if you put that in Energy Dashboard, you lose all the past data displayed in the Energy dashboard

**Comment by azerty9971** [comment]
Hello,
Can you all try v3.0.10 and let me know?

This is all caused because some people have a Paho MQTT version 1.x and some have a 2.x...

Thanks,
Azerty

**Comment by Tazrd** [comment]
I've tested my few devices and they all seem to work correctly. Thank you for your hard work!

**Comment by andreaskoelsch** [comment]
Updated, restarted twice, still have my plug shown twice.

**Comment by azerty9971** [comment]
> Updated, restarted twice, still have my plug shown twice.

Can you try to fully uninstall XT and the regular Tuya integration, then restart, then reinstall XT and reconfigure it?

It should fix the double entities...

Sorry for the inconvenience,
Azerty

**Comment by philspain72** [comment]
> > Updated, restarted twice, still have my plug shown twice.
> 
> Can you try to fully uninstall XT and the regular Tuya integration, then restart, then reinstall XT and reconfigure it?
> 
> It should fix the double entities...
> 
> Sorry for the inconvenience, Azerty

Will that not lose all the data from the sensors history?

**Comment by philspain72** [comment]
I deleted the integration and reinstalled, but its lost all sensors energy for the devices and changed them to consumption so you lose all the data in the energy dashboard for the last year

**Comment by andreaskoelsch** [comment]
Did you rename your entities? If so, just give them the name from before again

**Comment by philspain72** [comment]
I have just changed the consumption sensors to energy but nothing has changed not showing anything since the update in the energy  dashboard the old data is still there but nothing new yet still showing this

![Image](https://github.com/user-attachments/assets/0dcbe2b6-402c-411f-88c7-5fe9d8f6b01c)

**Comment by andreaskoelsch** [comment]
I don't understand what you have done and how it was before. Maybe someone else can help

**Comment by azerty9971** [comment]
> I have just changed the consumption sensors to energy but nothing has changed not showing anything since the update in the energy dashboard the old data is still there but nothing new yet still showing this
> 
> ![Image](https://github.com/user-attachments/assets/0dcbe2b6-402c-411f-88c7-5fe9d8f6b01c)

Hello,
I have those warnings too and everything is still working as expected...

I'll try to fix them soon but since it works they are not a priority...

By any chance, is this applicable to you?
https://github.com/azerty9971/xtend_tuya/blob/main/docs/renew_cloud_credentials.md

Have a nice day,
Azerty

**Comment by Leons77** [comment]
Everything works for me.

út 11. 3. 2025 v 10:56 odesílatel philspain72 ***@***.***>
napsal:

**Comment by philspain72** [comment]
> > i reinstalled and changed the new consumption sensor to the old name in energy dashboard. so for example sensor.water_valve_switch_consumption sensor.water_valve_switch_energy
> > Still not actually sure why it created a new name for the sensors in the update It would sure of being nice to have been told the entity names were going to change
> 
> It was actually not supposed to do that :/
> 
> Sorry for this

It's okay. I was just worried that I had lost all my data.
Thanks for your great work its appreciated

**Comment by andreaskoelsch** [comment]
Just updated to HA 2025.3.4 and Xtend Tuya 3.0.11. Again, all entities are duplicated breaking automations etc. Restored immediately. I'm not sure which one of the two updates was responsible for the problems. Please let us know when an update will be possible

**Comment by azerty9971** [comment]
Hello,
For the duplicated entities, can you try removing the configuration (in the configuration hub of XT), then do the update and then reconfigure the Tuya integration?

You should have all the history back with that procedure.
Sorry, about this, to be honest I have no idea why the entities keep changing, this should not happen :/

Have a nice day,
Azerty

**Comment by andreaskoelsch** [comment]
Thanks, that worked. I also tested out which update was responsible for this problem and it turned out it was the Xtend Tuya update that caused the issue, not the HA update
