### ISSUE TITLE
Tuya ME201W - Incorrect Liquid Level percentage displayed

### ISSUE THREAD

**Issue by ds4a** [azerty9971/xtend_tuya#279]
I have a ME201W water level sensor.

`
      "category": "ywcgq",
      "model": "ME201W",
      "name": "ME201W Level Sensor",
      "product_id": "4u9z7qg3je42rsw8",
`

It is connected to HA using the Xtend Tuya custom integration.
However the level percentage displayed in HA is incorrect by a factor of 10.
E.g: 95% actual, is correctly displayed by Tuya app and LocalTuya as 95%. However xtendTuya displays 9.5%

Here is the device debug data from tuya iot:
`max_set	Integer	
{
  "unit": "%",
  "min": 10,
  "max": 100,
  "scale": 0,
  "step": 1
}
mini_set	Integer	
{
  "unit": "%",
  "min": 0,
  "max": 100,
  "scale": 0,
  "step": 1
}
installation_height	Integer	
{
  "unit": "m",
  "min": 10,
  "max": 500,
  "scale": 2,
  "step": 1
}
liquid_depth_max	Integer	
{
  "unit": "m",
  "min": 10,
  "max": 500,
  "scale": 2,
  "step": 1
}
`

The installation_height (liquid_depth) UoM seems to be in meters when the device manual states it measures 0.1-5m of depth, or 10cm - 500cm. But I'm assuming that is handled by the scale setting? I'm just mentioning this in case it's important in some way, but is probably unrelated?

The output values from the device include the liquid_level_percent as the full, correct depth as an integer:

'{
  "result": [
    {
      "id": "bf6b9c3f027274f2924jspa",
      "status": [
        {
          "code": "liquid_state",
          "value": "normal"
        },
        {
          "code": "liquid_depth",
          "value": 40
        },
        {
          "code": "battery_percentage",
          "value": 50
        },
        {
          "code": "max_set",
          "value": 98
        },
        {
          "code": "mini_set",
          "value": 20
        },
        {
          "code": "installation_height",
          "value": 45
        },
        {
          "code": "liquid_depth_max",
          "value": 42
        },
        {
          "code": "liquid_level_percent",
          "value": 95
        }
      ]
    }
  ],
  "success": true,
  "t": 1745139665042,
  "tid": "fda82f601dc511f0942fe62c0c16d257"
}'

Bug report #162 talks about this sensor. They mention they are using xtendTuya 3.0.7 / 8.

I am using 3.0.11

**Comment by phmarra** [comment]
I have the same problem. 100% is 10%

**Comment by slipeer66** [comment]
The same thing happens to me

**Comment by azerty9971** [comment]
Hello,
Can you recheck on the latest release?

Thanks in advance,
Azerty

**Comment by phmarra** [comment]
Here in 3.0.12 it continues with the same error. To fix it I created a template helper entity:
{{ states('sensor.caixa_1000l_liquid_level') | float * 10 }}

**Comment by azerty9971** [comment]
Hello,
Can you post me the device diagnostics please? (see section 4 of https://github.com/azerty9971/xtend_tuya/issues/286)

Thanks!
Azerty

**Comment by azerty9971** [comment]
Can you retry with 3.1.0-beta.1 and let me know if it's now fixed?

Thanks in advance,
Azerty

**Comment by azerty9971** [comment]
Hello,
Can you try with the latest beta build?
(3.0.1-beta.3)

Hopefully it should fix it ...

Don't hesitate to export the device diagnostic after the update ;).

Thanks!
Azerty

**Comment by phmarra** [comment]
Here in version (3.0.1-beta.3) the same error continues.

**Comment by azerty9971** [comment]
can you post the device diagnostic on the latest beta please?
(just drag and drop the file in the comment section, it's easier for me to read this way ;))

Thanks in advance!
Azerty

**Comment by SR2MEDIA** [comment]
Hey Azerty,

still the same problem on v3.1.1 beta.3. 

For eg. 44% is shown as 4,4% liquid Level.
Relevant diagnostics attached.

I hope it will help.

Greetings Alex.

[config_entry-xtend_tuya.json](https://github.com/user-attachments/files/20034641/config_entry-xtend_tuya.json)

**Comment by azerty9971** [comment]
Hello,
Can you retry with the latest beta?

Thanks!
Azerty

**Comment by SR2MEDIA** [comment]
Hello Azerty, after the lates Updates still the same problem. 

Found the maybe faulty part in the Diagnostics : "state": "**4.1**", I think this should be "state": "**41**"

 {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.oltank_liquid_level",
            "state": "4.1",
            "attributes": {
              "unit_of_measurement": "%",
              "friendly_name": "\u00d6ltank Liquid level"
            },
            "last_changed": "2025-05-13T13:23:12.312961+00:00",
            "last_reported": "2025-05-13T13:23:13.284878+00:00",
            "last_updated": "2025-05-13T13:23:12.312961+00:00"
          }

I hope this will help a little bit more to find a solution. If you need any more Information, just let me know. 

Greetings Alex

**Comment by jbehem** [comment]
Hello,
Same issue here. Diagnostic file attached.
Thank you !
Julien

[tuya-01JE1E65AYBF18RH7KENVEWY9N-Capteur de niveau d'eau-0b5bdcca3daa55d74acce90c4ca1cd92.json](https://github.com/user-attachments/files/20645194/tuya-01JE1E65AYBF18RH7KENVEWY9N-Capteur.de.niveau.d.eau-0b5bdcca3daa55d74acce90c4ca1cd92.json)

**Comment by azerty9971** [comment]
Hello,
Can you retry with the latest beta?

Thanks :)
Azerty

**Comment by SR2MEDIA** [comment]
Azerty you solved it, it worked! Just one thing. I'm not 100% sure but I
think before it broke down it was, for example, 32% now it is 32,0% but I'm
very thankfully for this solution so far. Maybe there is a way to delete
the ,0.

azerty9971 ***@***.***> schrieb am Mo., 9. Juni 2025, 00:01:

**Comment by SR2MEDIA** [comment]
Azerty you solved it, it worked! Just one thing. I'm not 100% sure but I think before it broke down it was, for example, 32% now it is 32,0% but I'm very thankfull for this solution so far. Maybe you'll also find a way to delete the ,0. in the next main release. Greetings Alex

**Comment by jbehem** [comment]
It is fixed with the last beta. Thank you very much.
To remove the ,0 at the end of the value, edit the entity and change the
precision setting.

Julien
