### ISSUE TITLE
BLE Cabinet Lock not responding

### ISSUE THREAD

**Issue by Emporioo** [azerty9971/xtend_tuya#325]
Hi, first of all- I really appreciate the time you have put into this!

TLDR;
Is the basic Tuya BLE cabinet lock I have simply not supported with what I'm trying to achieve with it? (unlock via Home Assistant)

Example device:
https://www.aliexpress.com/item/1005004099310247.html

These seem like similar issues:
https://github.com/azerty9971/xtend_tuya/issues/269
https://github.com/azerty9971/xtend_tuya/issues/264
apologies if I'm rehashing the same problem.
---

My end goal was to use Alexa to control the lock, which I thought would be straight forward enough by using an additional Tuya Bluetooth Gateway which bridges BLE only deivce(s) to be WiFi controlled. This didn't work but alas, it only cost me $1 from Aliexpress... lol
Although it worked as far as being able to control it remotely but no chance to integrate it with Alexa as it simply doesn't discover the connected BLE device. I tried the scene functionality within Tuya/Life app to try and create a sort of automation/trick but no luck.

I went through a couple of the unofficial Tuya integrations before this one and got nowhere near as good of results compared to this one (ha_tuya_ble / tuya sensors / etc.)
This one immediately showed the control / battery with an automatic card with a lock/unlock button, I was quite awestruck as was about to give up with it but was sort of short lived after I realised the buttons didn't do anything,
Taking the batteries out the lock to turn it off/on makes the time last seen change as shown in one of the screenshots, but that's about it as far as any status change goes.

I have done all the Tuya Developer config/settings as instructed in these READMES and have also tried unbinding it from the gateway in order to control it directly but again, no luck.

<details><summary>Screenshots</summary>
<p>
<img src="https://github.com/user-attachments/assets/2007a24d-022e-44a2-a811-2d6ddd9e07ff">
<p></p>
<img src="https://github.com/user-attachments/assets/c9492609-07f7-4c89-aee9-ffea2584d1b4">
<p></p>
<img src="https://github.com/user-attachments/assets/e3ddffe4-fbf6-4c30-bde9-2f1a48a9870e">
<p></p>
<img src="https://github.com/user-attachments/assets/272bbdbc-86d3-4695-b52c-1f496bdf1e16">
<p></p>
</p>
</details> 

<details><summary>Diags</summary>
<p>
<pre>
<code>
`{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2025.5.2",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.13.3",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "4.4.302+",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "xtend_tuya": {
      "documentation": "https://github.com/azerty9971/xtend_tuya",
      "version": "3.1.0",
      "requirements": [
        "tuya-device-sharing-sdk==0.2.1",
        "tuya-iot-py-sdk==0.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xtend_tuya",
    "name": "Xtend Tuya",
    "after_dependencies": [
      "tuya"
    ],
    "codeowners": [
      "azerty9971"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg",
      "http"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://github.com/azerty9971/xtend_tuya",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/azerty9971/xtend_tuya/issues",
    "loggers": [
      "tuya_iot",
      "tuya_sharing"
    ],
    "requirements": [
      "tuya-device-sharing-sdk==0.2.1",
      "tuya-iot-py-sdk==0.6.6"
    ],
    "version": "3.1.0",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 3.3822027035057545e-05
    },
    "01JWBNSB3895ZZ2KAXQHFC0Z6R": {
      "wait_import_platforms": -0.039908441016450524,
      "wait_base_component": -0.0011022950056940317,
      "config_entry_setup": 1.897822399972938
    }
  },
  "data": {
    "mqtt_connected": null,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "bfa012oobkvhk3rg",
    "name": "Nintendo",
    "category": "ms",
    "local_key": "N7*o+&LB;3~FUx)a",
    "product_id": "matydudd",
    "product_name": "\u84dd\u7259\u62bd\u5c49\u9501",
    "online": true,
    "sub": true,
    "time_zone": "+01:00",
    "active_time": "2025-05-28T12:23:15+00:00",
    "create_time": "2025-05-28T12:23:15+00:00",
    "update_time": "2025-05-28T15:20:37+00:00",
    "function": {
      "unlock_method_modify": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 3
      },
      "unlock_method_delete": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 2
      },
      "unlock_method_create": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 1
      },
      "bluetooth_unlock": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 6
      }
    },
    "status_range": {
      "residual_electricity": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": -1,
          "max": 100,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 8
      },
      "unlock_ble": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 19
      },
      "unlock_method_modify": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 3
      },
      "unlock_method_delete": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 2
      },
      "alarm_lock": {
        "type": "Enum",
        "value": {
          "range": [
            "wrong_finger",
            "wrong_password",
            "wrong_card",
            "wrong_face",
            "tongue_bad",
            "too_hot",
            "unclosed_time",
            "tongue_not_out",
            "pry",
            "key_in",
            "low_battery",
            "power_off",
            "shock",
            "defense"
          ]
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 21
      },
      "bluetooth_unlock": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 6
      },
      "unlock_method_create": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 1
      }
    },
    "status": {
      "unlock_method_create": "",
      "unlock_method_delete": "",
      "unlock_method_modify": "",
      "bluetooth_unlock": "AQE=",
      "residual_electricity": 100,
      "unlock_ble": 1,
      "alarm_lock": "wrong_finger"
    },
    "local_strategy": {
      "8": {
        "value_convert": "default",
        "status_code": "residual_electricity",
        "config_item": {
          "statusFormat": "{\"residual_electricity\": \"$\"}",
          "valueDesc": "{\"unit\": \"\", \"min\": -1, \"max\": 100, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "matydudd"
        },
        "status_code_alias": [],
        "property_update": false,
        "use_open_api": false,
        "access_mode": "ro"
      },
      "19": {
        "value_convert": "default",
        "status_code": "unlock_ble",
        "config_item": {
          "statusFormat": "{\"unlock_ble\": \"$\"}",
          "valueDesc": "{\"unit\": \"\", \"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "matydudd"
        },
        "status_code_alias": [],
        "property_update": false,
        "use_open_api": false,
        "access_mode": "ro"
      },
      "3": {
        "value_convert": "default",
        "status_code": "unlock_method_modify",
        "config_item": {
          "statusFormat": "{\"unlock_method_modify\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "matydudd"
        },
        "status_code_alias": [],
        "property_update": false,
        "use_open_api": false,
        "access_mode": "rw"
      },
      "2": {
        "value_convert": "default",
        "status_code": "unlock_method_delete",
        "config_item": {
          "statusFormat": "{\"unlock_method_delete\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "matydudd"
        },
        "status_code_alias": [],
        "property_update": false,
        "use_open_api": false,
        "access_mode": "rw"
      },
      "21": {
        "value_convert": "default",
        "status_code": "alarm_lock",
        "config_item": {
          "statusFormat": "{\"alarm_lock\": \"$\"}",
          "valueDesc": "{\"range\": [\"wrong_finger\", \"wrong_password\", \"wrong_card\", \"wrong_face\", \"tongue_bad\", \"too_hot\", \"unclosed_time\", \"tongue_not_out\", \"pry\", \"key_in\", \"low_battery\", \"power_off\", \"shock\", \"defense\"]}",
          "valueType": "Enum",
          "enumMappingMap": {},
          "pid": "matydudd"
        },
        "status_code_alias": [],
        "property_update": false,
        "use_open_api": false,
        "access_mode": "ro"
      },
      "6": {
        "value_convert": "default",
        "status_code": "bluetooth_unlock",
        "config_item": {
          "statusFormat": "{\"bluetooth_unlock\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "matydudd"
        },
        "status_code_alias": [],
        "property_update": false,
        "use_open_api": false,
        "access_mode": "rw"
      },
      "1": {
        "value_convert": "default",
        "status_code": "unlock_method_create",
        "config_item": {
          "statusFormat": "{\"unlock_method_create\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "matydudd"
        },
        "status_code_alias": [],
        "property_update": false,
        "use_open_api": false,
        "access_mode": "rw"
      }
    },
    "home_assistant": {
      "name": "Nintendo",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.nintendo_operate_lock",
            "state": "unknown",
            "attributes": {
              "friendly_name": "Nintendo",
              "supported_features": 0
            },
            "last_changed": "2025-05-28T16:14:17.652846+00:00",
            "last_reported": "2025-05-28T18:09:16.047832+00:00",
            "last_updated": "2025-05-28T16:14:17.652846+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "battery",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.nintendo_battery",
            "state": "100.0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "%",
              "device_class": "battery",
              "friendly_name": "Nintendo Battery"
            },
            "last_changed": "2025-05-28T16:14:17.653091+00:00",
            "last_reported": "2025-05-28T16:23:30.927743+00:00",
            "last_updated": "2025-05-28T16:14:17.653091+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true,
    "multi_manager": {
      "mode": [
        "tuya_sharing",
        "tuya_iot"
      ]
    },
    "data_model": {
      "modelId": "000001y8tt",
      "services": [
        {
          "actions": [],
          "code": "",
          "description": "",
          "events": [],
          "name": "\u9ed8\u8ba4\u670d\u52a1",
          "properties": [
            {
              "abilityId": 1,
              "accessMode": "rw",
              "code": "unlock_method_create",
              "description": "\u3010\u5fc5\u9009\u3011App\u84dd\u7259\u8fd1\u8ddd\u79bb\u8fde\u63a5\u95e8\u9501\u540e\uff0c\u8fdb\u884c\u5f00\u95e8\u65b9\u5f0f\u7684\u521b\u5efa\u64cd\u4f5c\uff0c\u652f\u6301\u6307\u7eb9\u3001\u5bc6\u7801\u3001\u5361\u7b49\u65b9\u5f0f\u7684\u521b\u5efa",
              "name": "\u6dfb\u52a0\u5f00\u95e8\u65b9\u5f0f",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 2,
              "accessMode": "rw",
              "code": "unlock_method_delete",
              "description": "\u3010\u5fc5\u9009\u3011App\u84dd\u7259\u8fd1\u8ddd\u79bb\u8fde\u63a5\u95e8\u9501\u540e\uff0c\u8fdb\u884c\u5f00\u95e8\u65b9\u5f0f\u7684\u5220\u9664\u64cd\u4f5c\uff0c\u652f\u6301\u6307\u7eb9\u3001\u5bc6\u7801\u3001\u5361\u7b49\u65b9\u5f0f\u7684\u5220\u9664",
              "name": "\u5220\u9664\u5f00\u95e8\u65b9\u5f0f",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 3,
              "accessMode": "rw",
              "code": "unlock_method_modify",
              "description": "\u3010\u5fc5\u9009\u3011App\u84dd\u7259\u8fd1\u8ddd\u79bb\u8fde\u63a5\u95e8\u9501\u540e\uff0c\u8fdb\u884c\u5f00\u95e8\u65b9\u5f0f\u7684\u4fee\u6539\u64cd\u4f5c\uff0c\u652f\u6301\u6307\u7eb9\u3001\u5bc6\u7801\u3001\u5361\u7b49\u65b9\u5f0f\u7684\u4fee\u6539",
              "name": "\u4fee\u6539\u5f00\u95e8\u65b9\u5f0f",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 6,
              "accessMode": "rw",
              "code": "bluetooth_unlock",
              "description": "\u3010\u5fc5\u9009\u3011App\u8fd1\u8ddd\u79bb\u8fde\u63a5\u540e\uff0c\u8fdb\u884c\u89e3\u9501",
              "extensions": {
                "attribute": "512"
              },
              "name": "\u84dd\u7259\u89e3\u9501",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 8,
              "accessMode": "ro",
              "code": "residual_electricity",
              "description": "\u3010\u53ef\u9009\uff0c\u4f46\u5fc5\u987b\u4e8c\u9009\u4e00\u3011\u95e8\u9501\u4e0a\u62a5\u7535\u91cf\u767e\u5206\u6bd4\u3002\u5269\u4f59\u7535\u91cf\u4e0e\u7535\u91cf\u72b6\u6001\uff0c\u5fc5\u987b\u4e8c\u9009\u4e00   \u9ed8\u8ba4\u503c\u4e3a-1\u65f6\u4e0d\u663e\u793a\u7535\u91cf",
              "extensions": {
                "trigger": "direct"
              },
              "name": "\u5269\u4f59\u7535\u91cf",
              "typeSpec": {
                "max": 100,
                "min": -1,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 19,
              "accessMode": "ro",
              "code": "unlock_ble",
              "description": "\u3010\u5fc5\u987b\u3011\u8bf7\u7528\u8bb0\u5f55\u578b\u4e0a\u62a5\u6210\u529f\u4e0a\u62a5\uff1a\u6210\u5458+\u84dd\u7259\u5f00\u95e8+\u65f6\u95f4\uff08\u5f00\u95e8\u8bb0\u5f55\uff09",
              "extensions": {
                "trigger": "direct"
              },
              "name": "\u84dd\u7259\u89e3\u9501\u8bb0\u5f55",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 21,
              "accessMode": "ro",
              "code": "alarm_lock",
              "description": "\u3010\u5fc5\u9009\u30110=\u6307\u7eb9\u8bd5\u9519\u62a5\u8b66\u30011=\u5bc6\u7801\u8bd5\u9519\u62a5\u8b66\u30012=\u5361\u8bd5\u9519\u62a5\u8b66\u30013=\u4eba\u8138\u8bd5\u9519\u62a5\u8b66\u30014=\u5047\u9501\uff08\u9501\u820c\u5361\u4f4f\uff09\u30015=\u9ad8\u6e29\u62a5\u8b66\u30016=\u8d85\u65f6\u672a\u5173\u95e8\u30017=\u7535\u5b50\u9501\u820c\u672a\u5f39\u51fa\u30018=\u9632\u64ac\u62a5\u8b66 \u30019=\u94a5\u5319\u63d2\u5165\u300110=\u4f4e\u7535\u62a5\u8b66\u300111=\u7535\u91cf\u8017\u5c3d\u62a5\u8b66\u300112=\u9707\u52a8\u62a5\u8b66\u300113=\u5e03\u9632\u62a5\u8b66\u3002\u4f4e\u7535\u6682\u65f6\u4fdd\u7559\u4f7f\u7528\u5355\u72ec\u7684dp\u70b9\u7684\u8bbe\u8ba1\uff0c\u5982\u679c\u4f7f\u7528\u4e86\u672cdp\u70b9\u4e2d\u7684\u4f4e\u7535\u62a5\u8b66\u503c\uff0c\u5c31\u4e0d\u8981\u4f7f\u752811dp\u70b9",
              "extensions": {
                "trigger": "direct"
              },
              "name": "\u95e8\u9501\u544a\u8b66",
              "typeSpec": {
                "range": [
                  "wrong_finger",
                  "wrong_password",
                  "wrong_card",
                  "wrong_face",
                  "tongue_bad",
                  "too_hot",
                  "unclosed_time",
                  "tongue_not_out",
                  "pry",
                  "key_in",
                  "low_battery",
                  "power_off",
                  "shock",
                  "defense"
                ]
              }
            }
          ]
        }
      ]
    }
  }
}
</code>
</pre>
</p>
</details> 

Thank you
<i>Edits due to me being rubbish at formatting!</i>

**Comment by azerty9971** [comment]
Hello,
Thanks for your kind words :).

Can you confirm that you have performed the following steps?
https://github.com/azerty9971/xtend_tuya/blob/main/docs/configure_locks.md

For some reason, your lock doesn't show any "is locked or unlocked" status, by any chance is it one of those locks that when you press "unlock" unlocks for a few seconds and then relocks itself?

Anyway, can you try with the latest beta that I just published? It might be of help :)

Have a nice day,
Azerty

**Comment by Emporioo** [comment]
Hi Azerty,

Yes that's exactly right; the lock is locked by default and functions only to unlock briefly when activated.

Can confirm I've done the configure_locks.md guide

Have tried the latest beta and other than the card having a different type of visual button toggle, it still doesn't do anything

I stumbled upon this post while trying to troubleshoot it further:
https://github.com/make-all/tuya-local/issues/2059#issuecomment-2693126630

So I was successfully able to unlock the device via the Tuya device debugging page (any value unlocks it). I got excited thinking that I can surely integrate this into Home Assistant now but my knowledge of both .yaml and HA itself is very poor unfortunately as I've only just started using it...!
Do you think being able to send that code to unlock it has any bearing on it being able to be unlocked via your integration/HA? If so I will keep trying

![Image](https://github.com/user-attachments/assets/b0dfbd32-4491-4da6-be82-1078bbd6d412)

Thanks

**Comment by Emporioo** [comment]
Just to update, I've now got this working!
I spent FAR too long on this and very almost gave up ...Mainly due to my lack of programming skills 🤣

The way I've done it is not very elegant.
It no longer needs any sort of HA Tuya integration(s). The driving force behind it is interfacing directly with the Tuya API. It would be amazing if it's possible to combine this logic into this integration somehow though? Depending on how many people need it of course.

For those interested, here are some pointers:

- Needs the Tuya BLE device connected to a Tuya Gateway so that it can communicate via WiFi
- Use Tuya API explorer to interrogate needed values. Then change in the script below if req. 
- It 100% requires Tuya cloud to do this, so definitely not possible to make this work locally

The script I found to get this working was from here:
https://blog.rpanachi.com/howto-integrate-unsupported-tuya-devices-homeassistant

For my device specifically, I'd get the following error:

Traceback (most recent call last):
  File "/config/scripts/unlock.py", line 94, in <module>
    attributes   = get_device_properties(access_token, device_id)
  File "/config/scripts/unlock.py", line 77, in get_device_properties
    output = {j['code']: j['value'] for j in properties}
                         ~^^^^^^^^^

I substituted 'value' for 'dp_id'. This was the key to get rid of the errors. 
For the Tuya Cabinet Lock specifically, when interrogated with the Tuya API Explorer, the bluetooth_unlock is the code/mechanism for unlocking this device
(as mentioned in my above post, from that very, very helpful post from s0ftice)
Here is the output of mine:

      {
        "code": "bluetooth_unlock",
        "custom_name": "",
        "dp_id": 6,
        "time": 1749458254677,
        "type": "raw",
        "value": "xxxx"
      },

This is the full script after some AI tweaks to combine the logic:
<details><summary>Detail</summary>
<p>
<pre>
<code>
import sys
import hashlib
import hmac
import json
import urllib.parse
from urllib.request import urlopen, Request
from datetime import datetime

# Constants and credentials (consider moving these to a secure location)
EMPTY_BODY = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
BASE_URL   = "https://openapi.tuyaeu.com"
LOGIN_URL  = "/v1.0/token?grant_type=1"
client_id     = "YOUR_TUYA_CLIENT_ID"
client_secret = "YOUR_TUYA_SECRET"

def make_request(url, data=None, headers=None, method="GET"):
    """Make an HTTP request with optional data and headers."""
    if data and method.upper() == "GET":
        url = url + "?" + urllib.parse.urlencode(data)
        data = None
    encoded_data = data.encode("utf-8") if data else None
    request = Request(url, data=encoded_data, headers=headers or {}, method=method)
    with urlopen(request, timeout=10) as response:
        return response, response.read().decode("utf-8")

def get_timestamp(now=datetime.now()):
    """Return current timestamp (milliseconds) as a string."""
    return str(int(datetime.timestamp(now) * 1000))

def get_sign(payload, key):
    """Return the HMAC-SHA256 signature for a given payload."""
    byte_key = bytes(key, 'UTF-8')
    message = payload.encode("utf-8")
    sign = hmac.new(byte_key, message, hashlib.sha256).hexdigest()
    return sign.upper()

def get_access_token():
    """Retrieve the access token from Tuya API."""
    timestamp = get_timestamp()
    string_to_sign = client_id + timestamp + "GET\n" + EMPTY_BODY + "\n" + "\n" + LOGIN_URL
    signed_string = get_sign(string_to_sign, client_secret)
    headers = {
        "client_id": client_id,
        "sign": signed_string,
        "t": timestamp,
        "mode": "cors",
        "sign_method": "HMAC-SHA256",
        "Content-Type": "application/json"
    }
    _, body = make_request(BASE_URL + LOGIN_URL, headers=headers)
    return json.loads(body)["result"]["access_token"]

def send_unlock_command(access_token, device_id):
    """
    Send the unlock command to the device.
    The command payload is set to:
      {"code": "bluetooth_unlock", "value": "xxxx"} The value can actually be anything.
    """
    command_endpoint = f"/v1.0/devices/{device_id}/commands"
    full_url = BASE_URL + command_endpoint
    payload = json.dumps({"commands": [{"code": "bluetooth_unlock", "value": "xxxx"}]})
    timestamp = get_timestamp()
    payload_hash = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    string_to_sign = client_id + access_token + timestamp + "POST\n" + payload_hash + "\n" + "\n" + command_endpoint
    signed_string = get_sign(string_to_sign, client_secret)
    headers = {
        "client_id": client_id,
        "sign": signed_string,
        "access_token": access_token,
        "t": timestamp,
        "mode": "cors",
        "sign_method": "HMAC-SHA256",
        "Content-Type": "application/json"
    }
    _, body = make_request(full_url, data=payload, headers=headers, method="POST")
    return body

if len(sys.argv) != 2:
    raise SystemExit("Usage: python3 unlock.py device_id")

device_id = sys.argv[1]
access_token = get_access_token()
response = send_unlock_command(access_token, device_id)
print(response)

</pre>
</code>
</p>
</details> 

Before I found that script, I spent many hours unsuccessfully getting various AIs to create me one (as stated, I'm a Python noob!)
It kept failing with either invalid_token or various 'sign' errors but the script from the blog handles these critical components perfectly.

After confirming the script can successfully send an Unlock request, I (AI) made a HA shell command to trigger it.
I could then combine this to make it work with Alexa
_Unfortunately as I'm currently using the Nabu Casa 30 day trial to get Cloud functionality (which is required for Alexa compatibility), as soon as this expires it will break! I can't justify how much it costs monthly in order to keep using it._

Cheers,

**Comment by azerty9971** [comment]
Hello,
Thanks for your explanation, I'll implement this as a backup scenario in case the normal unlocking flow doesn't work ;).

Have you tried with the latest beta?
Because I've done quite some changes to locks on this one and in theory it should support a ton more locks :).

If you can, can we have a Google meet together to sort this out?

Thanks in advance,
Azerty

**Comment by Emporioo** [comment]
Hi still no luck with  v4.0.0-beta.3. If it did work I'd be kicking myself for all the hours I spent talking to AIs 🤣

I haven't used Google meet before but sure we can try that if you can send me a link or what not to join?

Thank you,

**Comment by azerty9971** [comment]
Sorry for the delay,
You can join me on: https://meet.google.com/ouv-tump-guo

Talk to you soon :).
Azerty

**Comment by azerty9971** [comment]
Hello,
This issue should be resolved in v4.0.0.

If it's not the case please reopen this issue.

Have a nice day,
Azerty
