### ISSUE TITLE
IBS-M2 Device Integration

### ISSUE THREAD

**Issue by EvanSchalton** [azerty9971/xtend_tuya#346]
Hello,

Last year I created [tuya-homeassistant-openapi](https://github.com/EvanSchalton/tuya-homeassistant-openapi) specifically to revert the API change in HA to use `openapi` and implement the parser for the IBS-M2 device. Your extension is much more feature rich, if you're interested in supporting the [device](https://github.com/EvanSchalton/tuya-homeassistant-openapi/blob/02eb7f2752723c41c2e622e48676a11607259d6e/custom_components/tuya_openapi/base.py#L173) I'd be happy to deprecate my extension and redirect traffic to xtend_tuya.

If I have some time later I'll look into submitting a PR for this, I think the could be a simple drop in, but I'd have to familiarize myself with your class inheritance from the offical Tuya app first (and I'm dragging my feet 😅 since I already have something working).

Regards,
-E

**Comment by azerty9971** [comment]
Hello,
I'd be delighted to implement this device:).

Could you export and post here the xtend_tuya diagnostic of this device?

It will make it easier for me to do a full implementation :).

Have a nice day,
Azerty

**Comment by EvanSchalton** [comment]
[tuya-40a34856644e62fd1047a80cc3321f4f-IBS_M2-b4f0de5b5cef16b4166d76cea2a4d69b.json](https://github.com/user-attachments/files/20712286/tuya-40a34856644e62fd1047a80cc3321f4f-IBS_M2-b4f0de5b5cef16b4166d76cea2a4d69b.json)

And here's the [code snippet](https://github.com/EvanSchalton/tuya-homeassistant-openapi/blob/02eb7f2752723c41c2e622e48676a11607259d6e/custom_components/tuya_openapi/base.py#L173) for parsing the raw:
```
decoded_bytes = base64.b64decode(data)
# TODO: Identify what the skipped bytes are in the base station data
_temperature, _humidity, _, battery = struct.Struct("<hHIb").unpack(
    decoded_bytes[1:11]
)
(temperature, humidity) = _temperature / 10.0, _humidity / 10.0

```

@azerty9971 would you mind tagging me in the PR; I'd be glad to use it to learn how you're managing classes so I can contribute in the future 👍

**Comment by EvanSchalton** [comment]
I had some free time tonight so I dug into your extension a bit; I'm not 100% confident on the regressions for the sensor type, but thought this would minimally be a step in the right direction.

This does work for the IBS-M2, I just can't verify I didn't break anything else (test case library would be a cool feature to add)

https://github.com/azerty9971/xtend_tuya/pull/348

**Comment by azerty9971** [comment]
Hello,
This has been merged and is now available on the latest beta version.

I still have some other work to do on other topics before posting a full-release but we are slowly getting there :).

I'll update this issue once it's done but if you want to try it out feel free to download the v4.0.1-beta.1 version (or later)

Have fun,
Azerty

**Comment by azerty9971** [comment]
Hello,
The release is now published:).

Have fun!
Azerty

**Comment by Olfo33** [comment]
Hello,
Everything is working perfectly. Thanks for the support! 👍

**Comment by FunkyOwl-Net** [comment]
How can i add the thermometer? Do i need to add it to Tuya-App or is it also possible to use the InkBird-App - I had the problem, that the hub and the pool thermometer couldnt be synced without InkBird-App, thats why i'm asking.

Thanks

**Comment by azerty9971** [comment]
@EvanSchalton : Can you help on this? I don't own this device so I can't really help you fully.

From what I remember, you need to first configure the thing in the InkBird app, then add it to the SmartLife app (where all will be in chinese), from there you should be able to import it in HA using XT...

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
Hello,
I think by then this has been resolved right?

If not feel free to respond and I'll reopen the issue.

Have a nice day,
Azerty

**Comment by DenisHE31** [comment]
Hello,

not possible for me to reconfigure again my IBS-M2 and IBS-P02R pool thermometer after a crash of my Home-Assistant old config...
The config in tuya dev looks ok, XtendTuya installed with HACS (and IBS-M2 is discovered) but impossible to have the thermo data.

I think that we need a clear tutorial from scratch, @EvanSchalton  :-)

Have a nice day

**Comment by azerty9971** [comment]
@Croock83 Did you find the solution to your issue?

Have a nice day,
Azerty

**Comment by Croock83** [comment]
@azerty9971 Sorry for deleting comment i just have second thought if I should post it before exploring each and every possibility.
For me it still doesnt work. Xtend Tuya shows only 1 temp sensor: -20C
Tuya Local shows correct sensorr (like Temperature probe 1 to 10) but all entities are unavailable. 
Maybe if other owners of IBS-M2 could comment if they can see correct vaules in HA then i would know if this is my issue only.
Thanks.

**Comment by azerty9971** [comment]
Can you come to the discord so that we can have a look at it together?

https://discord.gg/3EgfG5sZ4Y

Have a nice day,
Azerty

**Comment by Quiffster** [comment]
Another IBS-M2 User here.  I have the same issue as @Croock83 .
Added device to Tuya integration - shows just one sensor (showing -20).  2nd sensor is not showing.
Installed Xtend Tuya - doesn't appear at all in that list (though my other Tuya device does).
When i installed XT - i chose not to use OpenAPI (basically because i had an issue with the "Datacentre selection" in Tuya iot platform, and need to wait till i can create a new Cloud Project in a different DC).
Would that OpenAPI option have revealed the 2nd sensor?

EDIT:  Perhaps a bit hasty on this...  My IBS-M2 - since removing from Inkbird app, and adding to Tuya SL app - doesn't show the pool sensor.  Previously, the Inkbird app is where you add the 2nd sensor, and i cannot see (or decipher) how that's possible in the Tuya app (its all shown in Chinese) - any ideas how other users here have managed to add the probe via Tuya?
