### ISSUE TITLE
Error occurred loading flow for integration xtend_tuya: No module named 'homeassistant.components.tuya.event'

### ISSUE THREAD

**Issue by itispip** [azerty9971/xtend_tuya#427]
1st time install the integeration, run intot subjected error.

  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2025.5.3",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.13.3",
    "docker": true,
    "arch": "x86_64",
    "os_name": "Linux",
    "os_version": "6.6.87.2-microsoft-standard-WSL2",
    "run_as_root": true
  }

xtend Tuya version:  4.1.0

**Comment by azerty9971** [comment]
Hello,
Can you retry using version 4.1.1?

Have a nice day,
Azerty

**Comment by itispip** [comment]
> Hello, Can you retry using version 4.1.1?
> 
> Have a nice day, Azerty

4.1.1 still the same error. Downgrade to 4.0.9 will work good.

Setup failed for custom integration 'xtend_tuya': Unable to import component: No module named 'homeassistant.components.tuya.event'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 344, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1013, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 993, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 17, in <module>
    from .multi_manager.multi_manager import (
    ...<2 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 19, in <module>
    from .shared.shared_classes import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/shared/shared_classes.py", line 14, in <module>
    import custom_components.xtend_tuya.multi_manager.shared.multi_device_listener as mdl
  File "/config/custom_components/xtend_tuya/multi_manager/shared/multi_device_listener.py", line 12, in <module>
    import custom_components.xtend_tuya.util as util
  File "/config/custom_components/xtend_tuya/util.py", line 17, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
        TuyaDPType,
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.event import (
    ...<2 lines>...
    )
ModuleNotFoundError: No module named 'homeassistant.components.tuya.event'

**Comment by Foxcor** [comment]
I confirm the error.
I have the same. I'm still on 4.0.9

**Comment by azerty9971** [comment]
This is caused by the fact that the regular Tuya integration is not up to date (it lacks the "events.py" file)

There are 2 options, I can make the code work regardless of this, or you can upgrade your HA installation to the latest version and this error will disappear.

Please let me know if you are unable to upgrade and I'll make the code change so that you are not impacted :).

Have a nice day,
Azerty

**Comment by itispip** [comment]
> This is caused by the fact that the regular Tuya integration is not up to date (it lacks the "events.py" file)
> 

I am using XT+ Cloud mode. Do I need install OT to get rid of the error?

**Comment by azerty9971** [comment]
No, the regular Tuya integration is always embedded in HA (whether you use it or not).
And XT is using it to import the device definitions if you're not using it. But for that I have to fetch the files of Tuya, and in one of the later updates they added support for Events (push of a button, that sort of things) which I'm currently backporting into XT.

It was in theory not supposed to have any effect for now (but I was wrong about this)...

So no, you don't need to activate the regular Tuya integration, it won't change anything (and could mess up your entities...), simply updating HA (or if you can't just wait for the next release where I'll make some additional checks so that this is not an issue) should fix it :).

Sorry for the inconvenience,
Azerty

**Comment by itispip** [comment]
> No, the regular Tuya integration is always embedded in HA (whether you use it or not). 

Thank you for the details. I will wait for next release then. I cannot update to HA 202507 as the new release mess up some other integrations too.

Your integration is best of its kind. It's the only one with embedded support for many locks. This integration should deserve more downloads for Tuya Lock users.

**Comment by azerty9971** [comment]
Hello,
Can you retry on the latest BETA version? (4.1.2-beta.1)

Thanks!
Azerty

**Comment by ozcet** [comment]
Nope. Latest 4.1.2-beta still doesnt work....I have the same problem..Only 4.0.9 is ok...

**Comment by azerty9971** [comment]
Can you post the system log here?
The error must have changed in the latest beta (sorry, this one is hard for me to test).

Have a nice day,
Azerty

**Comment by ozcet** [comment]
Logger: homeassistant.setup
Source: setup.py:344
First occurred: 18:14:47 (1 occurrence)
Last logged: 18:14:47

Setup failed for custom integration 'xtend_tuya': Unable to import component: No module named 'homeassistant.components.tuya.event'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 344, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1013, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 993, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 17, in <module>
    from .multi_manager.multi_manager import (
    ...<2 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 19, in <module>
    from .shared.shared_classes import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/shared/shared_classes.py", line 14, in <module>
    import custom_components.xtend_tuya.multi_manager.shared.multi_device_listener as mdl
  File "/config/custom_components/xtend_tuya/multi_manager/shared/multi_device_listener.py", line 12, in <module>
    import custom_components.xtend_tuya.util as util
  File "/config/custom_components/xtend_tuya/util.py", line 17, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
        TuyaDPType,
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.event import (
    ...<2 lines>...
    )
ModuleNotFoundError: No module named 'homeassistant.components.tuya.event'





_______________________________________________________

**Comment by azerty9971** [comment]
Hello,
Can you update to 4.1.3-beta.2 and retry please?

Have a nice day,
Azerty

**Comment by ozcet** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 06:40:15 (2 occurrences)
Last logged: 06:40:21

Error setting up entry athensniriidon@gmail.com for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 47, in async_setup_entry
    await multi_manager.setup_entry(hass, entry)
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 110, in setup_entry
    plugin = await self.hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/multi_manager/tuya_sharing/init.py", line 61, in <module>
    from .ha_tuya_integration.platform_descriptors import get_tuya_platform_descriptors
  File "/config/custom_components/xtend_tuya/multi_manager/tuya_sharing/ha_tuya_integration/platform_descriptors.py", line 4, in <module>
    from ....ha_tuya_integration.tuya_integration_imports import (
    ...<15 lines>...
    )
ImportError: cannot import name 'EVENTS_TUYA' from 'custom_components.xtend_tuya.ha_tuya_integration.tuya_integration_imports' (/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py)

**Comment by azerty9971** [comment]
Hello,
Can you retry with 4.1.3-beta.3?

Hopefully this time it should work :).

Have a nice day,
Azerty

**Comment by ozcet** [comment]
Yes ! It works.....thank you

**Comment by itispip** [comment]
Thank you. 4.1.3-beta.3 worked for me too.
________________________________
