### ISSUE TITLE
Operate lock stoped working after recent updates

### ISSUE THREAD

**Issue by yurividal** [azerty9971/xtend_tuya#440]
Hi. I had previously done all the steps to get my smart lock to be reachable from HA. 
It used to work well, but recently, I can no longer unlock the door using HA. 

I can still see the status of the device and logs, but the unlock button shows this:

<img width="1525" height="953" alt="Image" src="https://github.com/user-attachments/assets/58557995-b004-4db8-914a-6885c72b6273" />

**Comment by azerty9971** [comment]
Hello,
sorry for this, can you post a device diagnostic here?

thanks in advance,
Azerty

**Comment by yurividal** [comment]
> Hello, sorry for this, can you post a device diagnostic here?
> 
> thanks in advance, Azerty

Here is my extend Tuya diagnostic for this device:

````
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2025.7.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.13.3",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.12.37+deb13-amd64",
    "container_arch": "amd64",
    "run_as_root": true
  },
  "custom_components": {
    "xtend_tuya": {
      "documentation": "https://github.com/azerty9971/xtend_tuya",
      "version": "4.1.1",
      "requirements": [
        "tuya-device-sharing-sdk==0.2.1",
        "tuya-iot-py-sdk==0.6.6"
      ]
    },
    "scheduler": {
      "documentation": "https://github.com/nielsfaber/scheduler-component",
      "version": "v0.0.0",
      "requirements": []
    },
    "homewhiz": {
      "documentation": "https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz",
      "version": "v0.5.8",
      "requirements": [
        "awsiotsdk",
        "bleak",
        "bleak_retry_connector",
        "dacite",
        "aiohttp",
        "bidict"
      ]
    },
    "samsungtv_smart": {
      "documentation": "https://github.com/ollo69/ha-samsungtv-smart",
      "version": "0.13.6",
      "requirements": [
        "websocket-client!=1.4.0,>=0.58.0",
        "wakeonlan>=2.0.0",
        "aiofiles>=0.8.0",
        "casttube>=0.2.1"
      ]
    },
    "auth_header": {
      "documentation": "https://github.com/BeryJu/hass-auth-header",
      "version": "1.4",
      "requirements": []
    },
    "hive": {
      "documentation": "https://www.home-assistant.io/integrations/hive",
      "version": "2021.7.0",
      "requirements": [
        "pyhive-integration==1.0.2"
      ]
    },
    "better_thermostat": {
      "documentation": "https://github.com/KartoffelToby/better_thermostat",
      "version": "1.7.0",
      "requirements": []
    },
    "dwains_dashboard": {
      "documentation": "https://dwainscheeren.github.io/dwains-lovelace-dashboard/",
      "version": "3.8.0",
      "requirements": []
    },
    "google_home": {
      "documentation": "https://github.com/leikoilja/ha-google-home",
      "version": "1.13.1",
      "requirements": [
        "glocaltokens==0.7.6"
      ]
    },
    "octopus_energy": {
      "documentation": "https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy",
      "version": "16.0.1",
      "requirements": [
        "pydantic"
      ]
    },
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.4.3",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tapo": {
      "documentation": "https://github.com/petretiandrea/home-assistant-tapo-p100",
      "version": "3.2.1",
      "requirements": [
        "plugp100==5.1.5"
      ]
    },
    "kia_uvo": {
      "documentation": "https://github.com/Hyundai-Kia-Connect/kia_uvo",
      "version": "2.43.0",
      "requirements": [
        "hyundai_kia_connect_api==3.43.0"
      ]
    },
    "auth_oidc": {
      "documentation": "https://github.com/christiaangoossens/hass-oidc-auth",
      "version": "0.6.2",
      "requirements": [
        "python-jose>=3.3.0",
        "aiofiles>=24.1.0",
        "jinja2>=3.1.4",
        "bcrypt>=4.2.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xtend_tuya",
    "name": "Xtend Tuya",
    "after_dependencies": [
      "tuya"
    ],
    "codeowners": [
      "azerty9971"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg",
      "http"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://github.com/azerty9971/xtend_tuya",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/azerty9971/xtend_tuya/issues",
    "loggers": [
      "tuya_iot",
      "tuya_sharing"
    ],
    "requirements": [
      "tuya-device-sharing-sdk==0.2.1",
      "tuya-iot-py-sdk==0.6.6"
    ],
    "version": "4.1.1",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 3.2638999982737005e-05
    },
    "01JSCVQD46VDCQ2CFAE5EZJXPC": {
      "wait_import_platforms": -0.3562928069877671,
      "config_entry_setup": 2.757755286002066
    }
  },
  "data": {
    "mqtt_connected": null,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "bfbfaab0751a241a5bkama",
    "name": "Front Door",
    "category": "jtmspro",
    "local_key": "REDACTED",
    "product_id": "srptwvak",
    "product_name": "Basic WFZIG Panel",
    "online": true,
    "sub": true,
    "time_zone": "+00:00",
    "active_time": "2025-03-22T19:10:41+00:00",
    "create_time": "2025-03-22T15:47:07+00:00",
    "update_time": "2025-07-28T12:06:47+00:00",
    "function": {
      "remote_no_pd_setkey": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 48
      },
      "remote_no_dp_key": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 49
      },
      "unlock_method_create": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 54
      },
      "unlock_method_delete": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 55
      },
      "normal_open_switch": {
        "type": "Boolean",
        "value": {},
        "property_update": false,
        "accessMode": "rw",
        "dpId": 76
      },
      "remote_unlock": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": true,
        "accessMode": "wr",
        "dpId": 21
      },
      "remote_unlock_switch": {
        "type": "Boolean",
        "value": {},
        "property_update": true,
        "accessMode": "wr",
        "dpId": 23
      },
      "password_creat": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": true,
        "accessMode": "wr",
        "dpId": 24
      },
      "password_delete": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": true,
        "accessMode": "wr",
        "dpId": 25
      },
      "password_update": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": true,
        "accessMode": "wr",
        "dpId": 26
      },
      "password_disable": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": true,
        "accessMode": "wr",
        "dpId": 27
      },
      "password_enable": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": true,
        "accessMode": "wr",
        "dpId": 28
      },
      "password_reset": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": true,
        "accessMode": "rw",
        "dpId": 39
      },
      "lock_gesture": {
        "type": "Boolean",
        "value": {},
        "property_update": true,
        "accessMode": "rw",
        "dpId": 53
      },
      "finger_input_times": {
        "type": "Integer",
        "value": {
          "max": 15,
          "min": 2,
          "scale": 0,
          "step": 1
        },
        "property_update": true,
        "accessMode": "rw",
        "dpId": 56
      },
      "update_all_finger": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 58
      },
      "update_all_password": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 59
      },
      "update_all_card": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "accessMode": "rw",
        "dpId": 60
      },
      "single_use_password": {
        "type": "Boolean",
        "value": {},
        "property_update": true,
        "accessMode": "rw",
        "dpId": 61
      }
    },
    "status_range": {
      "unlock_fingerprint": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 1
      },
      "unlock_password": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 2
      },
      "unlock_temporary": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 3
      },
      "unlock_dynamic": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 4
      },
      "unlock_card": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 5
      },
      "unlock_face": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 6
      },
      "open_close": {
        "type": "Boolean",
        "value": {},
        "property_update": false,
        "access_mode": "ro",
        "dpId": 8
      },
      "alarm_lock": {
        "type": "Enum",
        "value": {
          "range": [
            "wrong_finger",
            "wrong_password",
            "wrong_card",
            "wrong_face",
            "tongue_bad",
            "too_hot",
            "tongue_not_out",
            "pry",
            "key_in",
            "power_off",
            "shock",
            "unclosed_time",
            "low_battery"
          ]
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 9
      },
      "residual_electricity": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 10
      },
      "doorbell": {
        "type": "Boolean",
        "value": {},
        "property_update": false,
        "access_mode": "ro",
        "dpId": 14
      },
      "remote_result": {
        "type": "Boolean",
        "value": {},
        "property_update": false,
        "access_mode": "ro",
        "dpId": 22
      },
      "hijack": {
        "type": "Boolean",
        "value": {},
        "property_update": false,
        "access_mode": "ro",
        "dpId": 35
      },
      "unlock_remote": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        },
        "property_update": false,
        "access_mode": "ro",
        "dpId": 41
      },
      "anti_lock_outside": {
        "type": "Boolean",
        "value": {},
        "property_update": false,
        "access_mode": "ro",
        "dpId": 42
      },
      "remote_no_pd_setkey": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 48
      },
      "remote_no_dp_key": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 49
      },
      "unlock_method_create": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 54
      },
      "unlock_method_delete": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 55
      },
      "update_all_finger": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 58
      },
      "update_all_password": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 59
      },
      "update_all_card": {
        "type": "Raw",
        "value": {
          "maxlen": 128
        },
        "property_update": false,
        "access_mode": "rw",
        "dpId": 60
      },
      "normal_open_switch": {
        "type": "Boolean",
        "value": {},
        "property_update": false,
        "access_mode": "rw",
        "dpId": 76
      }
    },
    "status": {
      "unlock_fingerprint": 0,
      "unlock_password": 0,
      "unlock_temporary": 0,
      "unlock_dynamic": 0,
      "unlock_card": 0,
      "unlock_face": 0,
      "open_close": true,
      "alarm_lock": "wrong_password",
      "residual_electricity": 70,
      "doorbell": true,
      "remote_result": true,
      "hijack": false,
      "unlock_remote": 900,
      "anti_lock_outside": false,
      "remote_no_pd_setkey": "AAAB",
      "remote_no_dp_key": "AAAB",
      "unlock_method_create": "A/8BAAEAFAEA",
      "unlock_method_delete": "AwAAAAIADQH/",
      "update_all_finger": [
        16,
        17,
        18,
        19,
        20,
        10,
        11,
        12,
        13
      ],
      "update_all_password": [
        1
      ],
      "update_all_card": [
        14
      ],
      "normal_open_switch": false,
      "remote_unlock": null,
      "remote_unlock_switch": false,
      "password_creat": null,
      "password_delete": null,
      "password_update": null,
      "password_disable": null,
      "password_enable": null,
      "password_reset": null,
      "lock_gesture": false,
      "finger_input_times": 2,
      "single_use_password": false
    },
    "local_strategy": {
      "1": {
        "value_convert": "default",
        "status_code": "unlock_fingerprint",
        "config_item": {
          "statusFormat": "{\"unlock_fingerprint\": \"$\"}",
          "valueDesc": "{\"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "2": {
        "value_convert": "default",
        "status_code": "unlock_password",
        "config_item": {
          "statusFormat": "{\"unlock_password\": \"$\"}",
          "valueDesc": "{\"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "3": {
        "value_convert": "default",
        "status_code": "unlock_temporary",
        "config_item": {
          "statusFormat": "{\"unlock_temporary\": \"$\"}",
          "valueDesc": "{\"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "4": {
        "value_convert": "default",
        "status_code": "unlock_dynamic",
        "config_item": {
          "statusFormat": "{\"unlock_dynamic\": \"$\"}",
          "valueDesc": "{\"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "5": {
        "value_convert": "default",
        "status_code": "unlock_card",
        "config_item": {
          "statusFormat": "{\"unlock_card\": \"$\"}",
          "valueDesc": "{\"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "6": {
        "value_convert": "default",
        "status_code": "unlock_face",
        "config_item": {
          "statusFormat": "{\"unlock_face\": \"$\"}",
          "valueDesc": "{\"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "8": {
        "value_convert": "default",
        "status_code": "open_close",
        "config_item": {
          "statusFormat": "{\"open_close\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "9": {
        "value_convert": "default",
        "status_code": "alarm_lock",
        "config_item": {
          "statusFormat": "{\"alarm_lock\": \"$\"}",
          "valueDesc": "{\"range\": [\"wrong_finger\", \"wrong_password\", \"wrong_card\", \"wrong_face\", \"tongue_bad\", \"too_hot\", \"tongue_not_out\", \"pry\", \"key_in\", \"power_off\", \"shock\", \"unclosed_time\", \"low_battery\"]}",
          "valueType": "Enum",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "10": {
        "value_convert": "default",
        "status_code": "residual_electricity",
        "config_item": {
          "statusFormat": "{\"residual_electricity\": \"$\"}",
          "valueDesc": "{\"unit\": \"%\", \"min\": 0, \"max\": 100, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "14": {
        "value_convert": "default",
        "status_code": "doorbell",
        "config_item": {
          "statusFormat": "{\"doorbell\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "22": {
        "value_convert": "default",
        "status_code": "remote_result",
        "config_item": {
          "statusFormat": "{\"remote_result\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "35": {
        "value_convert": "default",
        "status_code": "hijack",
        "config_item": {
          "statusFormat": "{\"hijack\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "41": {
        "value_convert": "default",
        "status_code": "unlock_remote",
        "config_item": {
          "statusFormat": "{\"unlock_remote\": \"$\"}",
          "valueDesc": "{\"min\": 0, \"max\": 999, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "42": {
        "value_convert": "default",
        "status_code": "anti_lock_outside",
        "config_item": {
          "statusFormat": "{\"anti_lock_outside\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "ro"
      },
      "48": {
        "value_convert": "default",
        "status_code": "remote_no_pd_setkey",
        "config_item": {
          "statusFormat": "{\"remote_no_pd_setkey\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "49": {
        "value_convert": "default",
        "status_code": "remote_no_dp_key",
        "config_item": {
          "statusFormat": "{\"remote_no_dp_key\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "54": {
        "value_convert": "default",
        "status_code": "unlock_method_create",
        "config_item": {
          "statusFormat": "{\"unlock_method_create\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "55": {
        "value_convert": "default",
        "status_code": "unlock_method_delete",
        "config_item": {
          "statusFormat": "{\"unlock_method_delete\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "58": {
        "value_convert": "ms_dp_syn_alg",
        "status_code": "update_all_finger",
        "config_item": {
          "statusFormat": "{\"update_all_finger\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "59": {
        "value_convert": "ms_dp_syn_alg",
        "status_code": "update_all_password",
        "config_item": {
          "statusFormat": "{\"update_all_password\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "60": {
        "value_convert": "ms_dp_syn_alg",
        "status_code": "update_all_card",
        "config_item": {
          "statusFormat": "{\"update_all_card\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "76": {
        "value_convert": "default",
        "status_code": "normal_open_switch",
        "config_item": {
          "statusFormat": "{\"normal_open_switch\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "enumMappingMap": {},
          "pid": "srptwvak"
        },
        "property_update": false,
        "use_open_api": false,
        "status_code_alias": [],
        "access_mode": "rw"
      },
      "21": {
        "value_convert": "default",
        "status_code": "remote_unlock",
        "config_item": {
          "statusFormat": "{\"remote_unlock\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "wr",
        "status_code_alias": []
      },
      "23": {
        "value_convert": "default",
        "status_code": "remote_unlock_switch",
        "config_item": {
          "statusFormat": "{\"remote_unlock_switch\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "wr",
        "status_code_alias": []
      },
      "24": {
        "value_convert": "default",
        "status_code": "password_creat",
        "config_item": {
          "statusFormat": "{\"password_creat\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "wr",
        "status_code_alias": []
      },
      "25": {
        "value_convert": "default",
        "status_code": "password_delete",
        "config_item": {
          "statusFormat": "{\"password_delete\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "wr",
        "status_code_alias": []
      },
      "26": {
        "value_convert": "default",
        "status_code": "password_update",
        "config_item": {
          "statusFormat": "{\"password_update\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "wr",
        "status_code_alias": []
      },
      "27": {
        "value_convert": "default",
        "status_code": "password_disable",
        "config_item": {
          "statusFormat": "{\"password_disable\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "wr",
        "status_code_alias": []
      },
      "28": {
        "value_convert": "default",
        "status_code": "password_enable",
        "config_item": {
          "statusFormat": "{\"password_enable\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "wr",
        "status_code_alias": []
      },
      "39": {
        "value_convert": "default",
        "status_code": "password_reset",
        "config_item": {
          "statusFormat": "{\"password_reset\": \"$\"}",
          "valueDesc": "{\"maxlen\": 128}",
          "valueType": "Raw",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "rw",
        "status_code_alias": []
      },
      "53": {
        "value_convert": "default",
        "status_code": "lock_gesture",
        "config_item": {
          "statusFormat": "{\"lock_gesture\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "rw",
        "status_code_alias": []
      },
      "56": {
        "value_convert": "default",
        "status_code": "finger_input_times",
        "config_item": {
          "statusFormat": "{\"finger_input_times\": \"$\"}",
          "valueDesc": "{\"max\": 15, \"min\": 2, \"scale\": 0, \"step\": 1}",
          "valueType": "Integer",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "rw",
        "status_code_alias": []
      },
      "61": {
        "value_convert": "default",
        "status_code": "single_use_password",
        "config_item": {
          "statusFormat": "{\"single_use_password\": \"$\"}",
          "valueDesc": "{}",
          "valueType": "Boolean",
          "pid": "srptwvak"
        },
        "property_update": true,
        "use_open_api": true,
        "access_mode": "rw",
        "status_code_alias": []
      }
    },
    "home_assistant": {
      "name": "Front Door",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.front_door_operate_lock",
            "state": "unavailable",
            "attributes": {
              "restored": true,
              "friendly_name": "Operate lock",
              "supported_features": 0
            },
            "last_changed": "2025-07-29T11:33:58.384975+00:00",
            "last_reported": "2025-07-29T11:33:58.384975+00:00",
            "last_updated": "2025-07-29T11:33:58.384975+00:00"
          }
        },
        {
          "disabled": true,
          "disabled_by": "integration",
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": null
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "battery",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.front_door_battery",
            "state": "70.0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "%",
              "device_class": "battery",
              "friendly_name": "Front Door Battery"
            },
            "last_changed": "2025-07-29T11:33:54.185324+00:00",
            "last_reported": "2025-07-29T11:33:54.185324+00:00",
            "last_updated": "2025-07-29T11:33:54.185324+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.front_door_none",
            "state": "0.0",
            "attributes": {
              "friendly_name": "Front Door Fingerprint unlock user"
            },
            "last_changed": "2025-07-29T11:33:54.184276+00:00",
            "last_reported": "2025-07-29T11:33:54.188544+00:00",
            "last_updated": "2025-07-29T11:33:54.184276+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.front_door_password_unlock_user",
            "state": "0.0",
            "attributes": {
              "friendly_name": "Front Door Password unlock user"
            },
            "last_changed": "2025-07-29T11:33:54.184576+00:00",
            "last_reported": "2025-07-29T11:33:54.188647+00:00",
            "last_updated": "2025-07-29T11:33:54.184576+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.front_door_card_unlock_user",
            "state": "0.0",
            "attributes": {
              "friendly_name": "Front Door Card unlock user"
            },
            "last_changed": "2025-07-29T11:33:54.184838+00:00",
            "last_reported": "2025-07-29T11:33:54.188715+00:00",
            "last_updated": "2025-07-29T11:33:54.184838+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.front_door_face_unlock_user",
            "state": "0.0",
            "attributes": {
              "friendly_name": "Front Door Face unlock user"
            },
            "last_changed": "2025-07-29T11:33:54.185071+00:00",
            "last_reported": "2025-07-29T11:33:54.185071+00:00",
            "last_updated": "2025-07-29T11:33:54.185071+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "camera.front_door",
            "state": "idle",
            "attributes": {
              "access_token": "f13dc461dda478897b0c1182161289167ef1f005e948e7b67cc2649a7ae1bd29",
              "model_name": "Basic WFZIG Panel",
              "brand": "Tuya",
              "entity_picture": "**REDACTED**",
              "friendly_name": "Front Door",
              "supported_features": 2
            },
            "last_changed": "2025-07-29T11:33:54.296750+00:00",
            "last_reported": "2025-07-29T13:53:31.307248+00:00",
            "last_updated": "2025-07-29T13:53:31.307248+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true,
    "multi_manager": {
      "mode": [
        "tuya_sharing",
        "tuya_iot"
      ]
    },
    "data_model": {
      "modelId": "000002k2ti",
      "services": [
        {
          "actions": [],
          "code": "",
          "description": "",
          "events": [],
          "name": "\u9ed8\u8ba4\u670d\u52a1",
          "properties": [
            {
              "abilityId": 1,
              "accessMode": "ro",
              "code": "unlock_fingerprint",
              "description": "\u3010\u53ef\u9009\u3011\u6307\u7eb9\u5728\u95e8\u9501\u4e0a\u5f55\u5165\uff0c\u5f55\u5165\u5b8c\u6210\u540e\u7531\u786c\u4ef6\u5206\u914did\uff0c\u53d1\u751f\u6307\u7eb9\u89e3\u9501\u540e\uff0c\u95e8\u9501\u5c06\u4e0a\u62a5\u8be5dp\u70b9\u3002\u8bf7\u7528\u8bb0\u5f55\u578b\u4e0a\u62a5",
              "extensions": {
                "iconName": "icon-dp_lock",
                "trigger": "direct"
              },
              "name": "\u6307\u7eb9\u89e3\u9501",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 2,
              "accessMode": "ro",
              "code": "unlock_password",
              "description": "\u3010\u53ef\u9009\u3011\u666e\u901a\u5bc6\u7801\u5728\u95e8\u9501\u4e0a\u5f55\u5165\uff0c\u5f55\u5165\u5b8c\u6210\u540e\u7531\u786c\u4ef6\u5206\u914did\uff0c\u53d1\u751f\u666e\u901a\u5bc6\u7801\u89e3\u9501\u540e\uff0c\u95e8\u9501\u5c06\u4e0a\u62a5\u8be5dp\u70b9\u3002\u666e\u901a\u5bc6\u7801\u6307\u5728\u95e8\u9501\u786c\u4ef6\u4e0a\u521b\u5efa\u7684\u5bc6\u7801\uff0c\u4e0d\u5305\u542b\u901a\u8fc7app\u521b\u5efa\u7684\u4e34\u65f6\u5bc6\u7801\u3002\u8bf7\u7528\u8bb0\u5f55\u578b\u4e0a\u62a5\n",
              "extensions": {
                "iconName": "icon-dp_lock",
                "trigger": "direct"
              },
              "name": "\u666e\u901a\u5bc6\u7801\u89e3\u9501",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 3,
              "accessMode": "ro",
              "code": "unlock_temporary",
              "description": "\u3010\u53ef\u9009\u3011\u901a\u8fc7app\u521b\u5efa\u7684\u4e34\u65f6\u5bc6\u7801\uff0c\u4f7f\u7528\u8be5\u7c7b\u578b\u5f00\u95e8\u6210\u529f\u540e\u9700\u8981\u4e0a\u62a5\uff0c\u4e0a\u62a5\u7684id\u4e3a\u95e8\u9501\u7aefid\u3002\u8bf7\u7528\u8bb0\u5f55\u578b\u4e0a\u62a5\n",
              "extensions": {
                "iconName": "icon-dp_lock",
                "trigger": "direct"
              },
              "name": "\u4e34\u65f6\u5bc6\u7801\u89e3\u9501",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 4,
              "accessMode": "ro",
              "code": "unlock_dynamic",
              "description": "\u3010\u53ef\u9009\u3011\u4f7f\u7528\u52a8\u6001\u5bc6\u7801\u5f00\u95e8\u6210\u529f\u540e\uff0c\u8fdb\u884c\u4e0a\u62a5\uff0c\u53ea\u8981\u62a5\u6307\u5b9a\u6570\u5b571\u3002app\u663e\u793a\u7684\u65f6\u5019\uff0c\u53ea\u8981\u6709\u52a8\u6001\u5bc6\u7801\u8bb0\u5f55\uff0c\u4e0d\u663e\u793a\u5177\u4f53\u7f16\u53f7\u53ea\u663e\u793a\u7c7b\u578b\n",
              "extensions": {
                "iconName": "icon-dp_lock",
                "trigger": "direct"
              },
              "name": "\u52a8\u6001\u5bc6\u7801\u89e3\u9501",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 5,
              "accessMode": "ro",
              "code": "unlock_card",
              "description": "\u3010\u53ef\u9009\u3011\u5361\u7247\u5728\u95e8\u9501\u4e0a\u5f55\u5165\uff0c\u5f55\u5165\u5b8c\u6210\u540e\u7531\u786c\u4ef6\u5206\u914did\uff0c\u53d1\u751f\u5361\u7247\u89e3\u9501\u540e\uff0c\u95e8\u9501\u5c06\u4e0a\u62a5\u8be5dp\u70b9\u3002\u8bf7\u7528\u8bb0\u5f55\u578b\u4e0a\u62a5\n",
              "extensions": {
                "iconName": "icon-dp_lock",
                "trigger": "direct"
              },
              "name": "\u5361\u7247\u89e3\u9501",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 6,
              "accessMode": "ro",
              "code": "unlock_face",
              "description": "\u3010\u53ef\u9009\u3011\u4eba\u8138\u5728\u95e8\u9501\u4e0a\u5f55\u5165\uff0c\u5f55\u5165\u5b8c\u6210\u540e\u7531\u786c\u4ef6\u5206\u914did\uff0c\u53d1\u751f\u4eba\u8138\u89e3\u9501\u540e\uff0c\u95e8\u9501\u5c06\u4e0a\u62a5\u8be5dp\u70b9\u3002\u8bf7\u7528\u8bb0\u5f55\u578b\u4e0a\u62a5\n",
              "extensions": {
                "iconName": "icon-dp_lock",
                "attribute": "1024"
              },
              "name": "\u4eba\u8138\u8bc6\u522b\u89e3\u9501",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 8,
              "accessMode": "ro",
              "code": "open_close",
              "description": "\u3010\u53ef\u9009\u3011\u5982\u95e8\u9501\u786c\u4ef6\u652f\u6301\u5f00\u95e8/\u5173\u95e8\u4e8b\u4ef6\u76d1\u6d4b\u5219\u52fe\u9009\u8be5\u9879\uff0c\u5728\u5f00\u95e8\u8bb0\u5f55\u4e2d\uff0c\u52a0\u5165\u95e8\u7684\u5f00\u5173\u95e8\u4e8b\u4ef6\uff0c\u5e76\u4e14\u6700\u8fd1\u4e00\u6b21\u7684\u5f00\u5173\u95e8\u8bb0\u5f55\u53cd\u6620\u95e8\u5f53\u524d\u7684\u5f00\u5408\u72b6\u6001\u30020=\u5173\uff0c1=\u5f00\u3002\u8bf7\u4f7f\u7528\u8bb0\u5f55\u578b\u6570\u636e\u4e0a\u62a5\n",
              "extensions": {
                "iconName": "icon-fangzi1",
                "trigger": "direct"
              },
              "name": "\u5f00\u5173\u95e8\u4e8b\u4ef6",
              "typeSpec": {}
            },
            {
              "abilityId": 9,
              "accessMode": "ro",
              "code": "alarm_lock",
              "description": "\u3010\u5fc5\u9009\u30110=\u6307\u7eb9\u8bd5\u9519\u544a\u8b66\u30011=\u5bc6\u7801\u8bd5\u9519\u9ad8\u8b66\u30012=\u5361\u8bd5\u9519\u544a\u8b66\u30013=\u4eba\u8138\u8bd5\u9519\u544a\u8b66\u30014=\u5047\u9501\uff08\u9501\u820c\u5361\u4f4f\uff09\u30015=\u9ad8\u6e29\u544a\u8b66\u30016=\u8d85\u65f6\u672a\u5173\u95e8\u30017=\u7535\u5b50\u9501\u820c\u672a\u5f39\u51fa\u30018=\u9632\u64ac\u544a\u8b66 \u30019=\u94a5\u5319\u63d2\u5165\u300110=\u4f4e\u7535\u544a\u8b66\u300111=\u7535\u91cf\u8017\u5c3d\u544a\u8b66\u300112=\u9707\u52a8\u544a\u8b66\u3002\n",
              "extensions": {
                "iconName": "icon-Trigger",
                "attribute": "512",
                "trigger": "direct"
              },
              "name": "\u544a\u8b66",
              "typeSpec": {
                "range": [
                  "wrong_finger",
                  "wrong_password",
                  "wrong_card",
                  "wrong_face",
                  "tongue_bad",
                  "too_hot",
                  "tongue_not_out",
                  "pry",
                  "key_in",
                  "power_off",
                  "shock",
                  "unclosed_time",
                  "low_battery"
                ]
              }
            },
            {
              "abilityId": 10,
              "accessMode": "ro",
              "code": "residual_electricity",
              "description": "\u3010\u5fc5\u9009\u3011\u95e8\u9501\u4e0a\u62a5\u7535\u91cf\u767e\u5206\u6bd4\n",
              "extensions": {
                "iconName": "icon-dp_battery",
                "attribute": "512",
                "trigger": "direct"
              },
              "name": "\u5269\u4f59\u7535\u91cf",
              "typeSpec": {
                "max": 100,
                "min": 0,
                "scale": 0,
                "step": 1,
                "unit": "%"
              }
            },
            {
              "abilityId": 14,
              "accessMode": "ro",
              "code": "doorbell",
              "description": "\u3010\u53ef\u9009\u3011\u652f\u6301\u95e8\u94c3\u529f\u80fd\u7684\u95e8\u9501\uff0c\u5728\u6309\u952e\u540e\u95e8\u9501\u786c\u4ef6\u53d1\u51fa\u95e8\u94c3\u58f0\uff0capp\u6536\u5230\u63d0\u9192\n",
              "extensions": {
                "iconName": "icon-dp_voice",
                "trigger": "direct"
              },
              "name": "\u95e8\u94c3",
              "typeSpec": {}
            },
            {
              "abilityId": 21,
              "accessMode": "wr",
              "code": "remote_unlock",
              "description": "\u3010\u53ef\u9009\u3011\u4e0b\u53d1\u5f00\u95e8\u6307\u4ee4\u7684\u65f6\u5019\uff0c\u5e26\u6709\u5bc6\u7801\u5230\u95e8\u9501\u672c\u5730\u6821\u9a8c\uff0c\u6821\u9a8c\u901a\u8fc7\u540e\u95e8\u9501\u624d\u89e3\u9501\u3002\u95e8\u9501\u6536\u5230\u8be5dp\u540e\uff0c\u9700\u8981\u56de\u590d22\uff0c\u5982\u679c\u5bc6\u7801\u6b63\u786e\u5f00\u95e8\u6210\u529f\uff0c\u9700\u8981\u56de\u590d38\u548c41\n",
              "extensions": {
                "iconName": "icon-dp_loop",
                "trigger": "direct"
              },
              "name": "\u542b\u5bc6\u8fdc\u7a0b\u5f00\u95e8\u6307\u4ee4",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 22,
              "accessMode": "ro",
              "code": "remote_result",
              "description": "\u3010\u53ef\u9009\u3011\u4e0a\u62a5\u5f00\u95e8\u7ed3\u679c\uff0c\u95e8\u9501mcu\u9700\u56de\u590d\u8be5dp\uff0cture\u6216false\n",
              "extensions": {
                "iconName": "icon-dp_loop",
                "trigger": "direct"
              },
              "name": "\u8fdc\u7a0b\u5f00\u95e8\u6307\u4ee4\u53cd\u9988",
              "typeSpec": {}
            },
            {
              "abilityId": 23,
              "accessMode": "wr",
              "code": "remote_unlock_switch",
              "description": "\u3010\u53ef\u9009\u3011\u901a\u8fc7app\u8fdb\u884c\u8bbe\u7f6e\uff0c\u53ef\u4ee5\u7981\u7528\uff0c\u542f\u7528\u8fdc\u7a0b\u5f00\u95e8\u529f\u80fd\uff1b\u7981\u7528\u8fdc\u7a0b\u5f00\u95e8\u529f\u80fd\u540e\uff0c\u65e0\u6cd5\u901a\u8fc7app\u8fdb\u884c\u8fdc\u7a0b\u5f00\u95e8\uff0c\u8fdb\u884c\u8be5\u64cd\u4f5c\u95e8\u9501\u786c\u4ef6\u4f1a\u62d2\u7edd\uff0c\u91cd\u65b0\u542f\u7528\u540e\u624d\u80fd\u8fdb\u884c\u8fdc\u7a0b\u5f00\u95e8\u3002\u7981\u7528\u8fdc\u7a0b\u5f00\u95e8\uff0c\u4f1a\u4e0b\u53d1dp48\uff0c\u4f7f\u5f97mcu\u7aef\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\u5bc6\u94a5\u5931\u6548\u3002\n",
              "extensions": {
                "iconName": "icon-HomeArm"
              },
              "name": "\u7981\u7528\u8fdc\u7a0b\u5f00\u95e8",
              "typeSpec": {}
            },
            {
              "abilityId": 24,
              "accessMode": "wr",
              "code": "password_creat",
              "description": "\u3010\u53ef\u9009\u3011app/web\u53d1\u8d77\u64cd\u4f5c\uff0c\u8c03\u7528\u670d\u52a1\u7aef\u63a5\u53e3\uff0c\u670d\u52a1\u5668\u8f6c\u6362\u4e3adp\u70b9\n",
              "extensions": {
                "iconName": "icon-dp_add"
              },
              "name": "\u521b\u5efa\u4e34\u65f6\u5bc6\u7801",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 25,
              "accessMode": "wr",
              "code": "password_delete",
              "description": "\u3010\u53ef\u9009\u3011app/web\u53d1\u8d77\u64cd\u4f5c\uff0c\u8c03\u7528\u670d\u52a1\u7aef\u63a5\u53e3\uff0c\u670d\u52a1\u5668\u8f6c\u6362\u4e3adp\u70b9\n",
              "extensions": {
                "iconName": "icon-dp_reduce"
              },
              "name": "\u5220\u9664\u4e34\u65f6\u5bc6\u7801",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 26,
              "accessMode": "wr",
              "code": "password_update",
              "description": "\u3010\u53ef\u9009\u3011app/web\u53d1\u8d77\u64cd\u4f5c\uff0c\u8c03\u7528\u670d\u52a1\u7aef\u63a5\u53e3\uff0c\u670d\u52a1\u5668\u8f6c\u6362\u4e3adp\u70b9\n",
              "extensions": {
                "iconName": "icon-dp_home2"
              },
              "name": "\u4fee\u6539\u4e34\u65f6\u5bc6\u7801",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 27,
              "accessMode": "wr",
              "code": "password_disable",
              "description": "\u3010\u53ef\u9009\u3011app/web\u53d1\u8d77\u64cd\u4f5c\uff0c\u8c03\u7528\u670d\u52a1\u7aef\u63a5\u53e3\uff0c\u670d\u52a1\u5668\u8f6c\u6362\u4e3adp\u70b9\n",
              "extensions": {
                "iconName": "icon-dp_home2"
              },
              "name": "\u51bb\u7ed3\u4e34\u65f6\u5bc6\u7801",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 28,
              "accessMode": "wr",
              "code": "password_enable",
              "description": "\u3010\u53ef\u9009\u3011app/web\u53d1\u8d77\u64cd\u4f5c\uff0c\u8c03\u7528\u670d\u52a1\u7aef\u63a5\u53e3\uff0c\u670d\u52a1\u5668\u8f6c\u6362\u4e3adp\u70b9\n",
              "extensions": {
                "iconName": "icon-dp_home2"
              },
              "name": "\u89e3\u51bb\u4e34\u65f6\u5bc6\u7801",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 35,
              "accessMode": "ro",
              "code": "hijack",
              "description": "\u3010\u53ef\u9009\u3011\u8be5\u529f\u80fd\u9ed8\u8ba4\u4e0d\u9700\u8981\u786c\u4ef6\u5b9e\u73b0\uff0c\u95e8\u9501\u4e0d\u7528\u505a\u52ab\u6301\u5224\u65ad\uff0c\u53ea\u8981\u5728app\u4e0a\u6807\u8bb0\u89e3\u9501id\u5373\u53ef\n",
              "extensions": {
                "iconName": "icon-guanjia",
                "trigger": "direct"
              },
              "name": "\u52ab\u6301\u62a5\u8b66",
              "typeSpec": {}
            },
            {
              "abilityId": 39,
              "accessMode": "rw",
              "code": "password_reset",
              "description": "\u3010\u5fc5\u9009\u3011\u5f53app\u5bf9\u95e8\u9501\u8fdb\u884c\u6062\u590d\u51fa\u5382\u8bbe\u7f6e\u65f6\uff0c\u4e91\u7aef\u4e0b\u53d1\u6307\u4ee4\u7ed9\u95e8\u9501\uff0c\u95e8\u9501\u6e05\u9664\u672c\u5730\u7684\u4e34\u65f6\u5bc6\u7801\u3002\u5982\u679c\u95e8\u9501\u672c\u5730\u8fdb\u884c\u6062\u590d\u51fa\u5382\u8bbe\u7f6e\uff0c\u6e05\u9664\u4e86\u672c\u5730\u7684\u4e34\u65f6\u5bc6\u7801\uff0c\u9700\u8981\u4e0a\u62a5\u8be5dp\u70b9\u4e91\u7aef\uff0c\u786e\u4fdd\u4e91\u7aef\u7684\u4e34\u65f6\u5bc6\u7801\u8bb0\u5f55\u548c\u672c\u5730\u4fdd\u6301\u4e00\u81f4\u3002\u5982\u679c\u672c\u5730\u6062\u590d\u51fa\u5382\u8bbe\u7f6e\u65f6\uff0c\u4e0a\u62a5\u8be539\u5931\u8d25\uff0c\u9700\u8981\u5728\u4e0b\u6b21\u91cd\u65b0\u914d\u7f51\u540e\u4e0a\u62a539\n",
              "extensions": {
                "iconName": "icon-dp_reduce"
              },
              "name": "\u6e05\u9664\u95e8\u9501\u4e34\u65f6\u5bc6\u7801",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 41,
              "accessMode": "ro",
              "code": "unlock_remote",
              "description": "\u3010\u53ef\u9009\u3011\u5f53\u95e8\u9501\u4f7f\u7528\u8fdc\u7a0b\u5f00\u95e8\u540e\uff0c\u9700\u89811\u3001\u56de\u590d\u8fdc\u7a0b\u5f00\u95e8\u6210\u529f\u7684\u6307\u4ee4\uff0c\u5373dp\u70b922\uff1b   2\u3001\u4e0a\u62a5\u95e8\u88ab\u6253\u5f00\uff0c\u5373dp\u70b938 \uff1b3\u3001\u4e0a\u62a5\u8fdc\u7a0b\u5f00\u95e8\u7684\u8bb0\u5f55\uff0c\u5373dp\u70b941\n",
              "name": "\u8fdc\u7a0b\u5f00\u95e8\u8bb0\u5f55",
              "typeSpec": {
                "max": 999,
                "min": 0,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 42,
              "accessMode": "ro",
              "code": "anti_lock_outside",
              "description": "\u3010\u53ef\u9009\u3011\u5728\u95e8\u9501\u5916\u90e8\uff0c\u8fdb\u884c\u4e0a\u63d0\u53cd\u9501\u540e\uff0c\u4e0a\u62a5\u8be5dp\u70b9\u3002\u53cd\u9501=ture\uff0c\u672a\u53cd\u9501=false\n",
              "extensions": {
                "iconName": "icon-dp_lock",
                "attribute": "1280",
                "trigger": "direct"
              },
              "name": "\u4e0a\u63d0\u53cd\u9501",
              "typeSpec": {}
            },
            {
              "abilityId": 48,
              "accessMode": "rw",
              "code": "remote_no_pd_setkey",
              "description": "\u3010\u53ef\u9009\u3011\u8be5\u529f\u80fd\u4e3a\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\u5b89\u5168\u65b9\u6848\u65b0\u589edp\uff1a\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\u529f\u80fd\u9700\u8981\u52fe\u9009\u8be5dp\uff0c\u7531\u670d\u52a1\u7aef\u4e0b\u53d1\u8be5dp\uff0c\u5e26\u5bc6\u94a5\u5230\u95e8\u9501\u7aef\u3002\u5f53\u524d\u903b\u8f91\uff1a\u95e8\u9501\u6536\u5230dp48\u540e\uff0c\u5b58\u50a8\u8be5\u8fdc\u7a0b\u5f00\u95e8\u5bc6\u94a5\u3002\u95e8\u9501\u6536\u5230\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\u6307\u4ee4dp49\u540e\uff0c\u6821\u9a8c\u8be5\u5bc6\u94a5\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u65b0\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8-\u8bbe\u7f6e\u514d\u5bc6\u5bc6\u94a5",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 49,
              "accessMode": "rw",
              "code": "remote_no_dp_key",
              "description": "\u3010\u53ef\u9009\u3011\u8be5dp\u4e0edp48\u914d\u5408\u4f7f\u7528\u3002\u65b0\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\u4e0b\u53d1\u529f\u80fd\u4f7f\u7528 \u65b0\u7684dp49 \uff0c\u4e0b\u53d1\u8be5dp\u9700\u8981mcu\u7aef\u89e3\u6790\u6570\u636e\u683c\u5f0f\u3002\u539fdp40\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\u5f03\u7528\u3002\n\u65b0\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\uff0c\u5148\u7531\u670d\u52a1\u7aef\u4e0b\u53d1\u5b89\u5168\u5bc6\u94a5\uff1adp48\uff0cmcu\u7aef\u5b58\u50a8\u8be5\u5bc6\u94a5\u3002\u7136\u540e\u9762\u677f\u7aef\u53d1\u8d77dp49\uff0c\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8\uff0cmcu\u5219\u56de\u590ddp49\uff0c\u5982\u679c\u5f00\u95e8\u6210\u529f\u56de\u590ddp22\uff1a\u8fdc\u7a0b\u5f00\u95e8\u8bb0\u53cd\u9988 \u548cdp41\uff1a\u8fdc\u7a0b\u5f00\u95e8\u89e3\u9501\u8bb0\u5f55\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u65b0\u514d\u5bc6\u8fdc\u7a0b\u5f00\u95e8-\u5b89\u5168\u65b9\u6848",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 53,
              "accessMode": "rw",
              "code": "lock_gesture",
              "description": "\u3010\u53ef\u9009\u3011\u52fe\u9009\u8be5dp\u540e\u516c\u7248\u9762\u677f\u53ef\u5f00\u542f\u624b\u52bf\u5bc6\u7801\u529f\u80fd\u3002\u6bcf\u6b21\u8fdb\u5165\u9762\u677f\u540e\u9700\u8981\u8fdb\u884c\u4e8c\u6b21\u624b\u52bf\u6821\u9a8c\uff0c\u63d0\u5347\u9762\u677f\u7684\u5b89\u5168\u6027\u3002\u5728\u9762\u677f\u8bbe\u7f6e\u9875\uff0cC\u7aef\u7528\u6237\u53ef\u81ea\u884c\u5173\u95ed\u548c\u5f00\u542f\u624b\u52bf\u6821\u9a8c\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u624b\u52bf\u6821\u9a8c",
              "typeSpec": {}
            },
            {
              "abilityId": 54,
              "accessMode": "rw",
              "code": "unlock_method_create",
              "description": "\u3010\u5fc5\u9009\u3011\u7531App\u7aef\u53d1\u8d77\u6dfb\u52a0\u5f00\u95e8\u65b9\u5f0f\u3002\u5728\u95e8\u9501\u9762\u677f\u6210\u5458\u7ba1\u7406\u5217\u8868\u9009\u62e9\u76f8\u5e94\u7684\u5bb6\u5ead\u6210\u5458\uff0c\u7136\u540eApp\u53d1\u8d77\u6dfb\u52a0\u6307\u7eb9\u3001\u5361\u548c\u5bc6\u7801\u7b49\u5f00\u95e8\u65b9\u5f0f\u3002",
              "extensions": {
                "attribute": "640"
              },
              "name": "\u6dfb\u52a0\u5f00\u95e8\u65b9\u5f0f",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 55,
              "accessMode": "rw",
              "code": "unlock_method_delete",
              "description": "\u3010\u5fc5\u9009\u3011\u7531App\u7aef\u53d1\u8d77\u5220\u9664\u5f00\u95e8\u65b9\u5f0f\u3002\u5728\u95e8\u9501\u9762\u677f\u6210\u5458\u7ba1\u7406\u5217\u8868\u9009\u62e9\u76f8\u5e94\u7684\u5bb6\u5ead\u6210\u5458\u548c\u5bf9\u5e94\u7684\u5f00\u95e8\u65b9\u5f0f\uff0c\u7136\u540eApp\u53d1\u8d77\u5220\u9664\u6307\u7eb9\u3001\u5361\u548c\u5bc6\u7801\u7b49\u5f00\u95e8\u65b9\u5f0f\u3002\u56e0\u4e3a\u5f00\u95e8\u65b9\u5f0f\u4e0e\u5bb6\u5ead\u6210\u5458\u7ed1\u5b9a\uff0c\u6240\u4ee5\u5728App\u79fb\u9664\u5bb6\u5ead\u6210\u5458\u540e\uff0c\u4e91\u7aef\u4e5f\u4f1a\u4e0b\u53d1\u5220\u9664\u5f00\u95e8\u65b9\u5f0f\u7684dp\u5230\u8bbe\u5907\u7aef\u3002",
              "extensions": {
                "attribute": "640"
              },
              "name": "\u5220\u9664\u5f00\u95e8\u65b9\u5f0f",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 56,
              "accessMode": "rw",
              "code": "finger_input_times",
              "description": "\u3010\u53ef\u9009\u3011\u6dfb\u52a0\u5f00\u95e8\u65b9\u5f0f\uff0c\u53ef\u4ee5\u9009\u62e9\u6dfb\u52a0\u6307\u7eb9\u7684\u6b21\u6570\u3002\u4e00\u822c\u4e3a2-15\u6b21\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u6dfb\u52a0\u6307\u7eb9\u8f93\u5165\u6b21\u6570",
              "typeSpec": {
                "max": 15,
                "min": 2,
                "scale": 0,
                "step": 1
              }
            },
            {
              "abilityId": 58,
              "accessMode": "rw",
              "code": "update_all_finger",
              "description": "\u3010\u53ef\u9009\u3011\u5f53\u6709\u672c\u5730\u6dfb\u52a0\u7684\u5f00\u95e8\u65b9\u5f0f-\u6307\u7eb9\u65f6\uff0c\u95e8\u9501\u9700\u8981\u4e0a\u62a5\u8be5dp\uff0c\u540c\u6b65\u5168\u90e8\u6307\u7eb9id\u3002\u540c\u6b65\u5230\u4e91\u7aef\u540e\uff0c\u9762\u677f\u7aef\u4f1a\u5c55\u793a\u672a\u7ed1\u5b9a\u5f00\u95e8\u4eba/\u5bb6\u5ead\u6210\u5458\u7684\u6307\u7eb9id\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u540c\u6b65\u6240\u6709\u6307\u7eb9\u7f16\u53f7",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 59,
              "accessMode": "rw",
              "code": "update_all_password",
              "description": "\u3010\u53ef\u9009\u3011\u5f53\u6709\u672c\u5730\u6dfb\u52a0\u7684\u5f00\u95e8\u65b9\u5f0f-\u5bc6\u7801\u65f6\uff0c\u95e8\u9501\u9700\u8981\u4e0a\u62a5\u8be5dp\uff0c\u540c\u6b65\u5168\u90e8\u5bc6\u7801id\u3002\u540c\u6b65\u5230\u4e91\u7aef\u540e\uff0c\u9762\u677f\u7aef\u4f1a\u5c55\u793a\u672a\u7ed1\u5b9a\u5f00\u95e8\u4eba/\u5bb6\u5ead\u6210\u5458\u7684\u5bc6\u7801id\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u540c\u6b65\u6240\u6709\u5bc6\u7801\u7f16\u53f7",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 60,
              "accessMode": "rw",
              "code": "update_all_card",
              "description": "\u3010\u53ef\u9009\u3011\u5f53\u6709\u672c\u5730\u6dfb\u52a0\u7684\u5f00\u95e8\u65b9\u5f0f-\u5361\u65f6\uff0c\u95e8\u9501\u9700\u8981\u4e0a\u62a5\u8be5dp\uff0c\u540c\u6b65\u5168\u90e8\u5361id\u3002\u540c\u6b65\u5230\u4e91\u7aef\u540e\uff0c\u9762\u677f\u7aef\u4f1a\u5c55\u793a\u672a\u7ed1\u5b9a\u5f00\u95e8\u4eba/\u5bb6\u5ead\u6210\u5458\u7684\u5361id\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u540c\u6b65\u6240\u6709\u5361\u7f16\u53f7",
              "typeSpec": {
                "maxlen": 128
              }
            },
            {
              "abilityId": 61,
              "accessMode": "rw",
              "code": "single_use_password",
              "description": "\u8be5dp\u7528\u4e8e\u63a7\u5236\u9762\u677f\u7aef\u663e\u793a\u4e00\u6b21\u6027\u5bc6\u7801\uff0c\u9ed8\u8ba4\u4e3atrue\u3002\u5982\u679c\u52fe\u9009\u8be5dp\uff0c\u5219\u6709\u4e00\u6b21\u6027\u5bc6\u7801\u529f\u80fd\uff0c\u5982\u679c\u4e0d\u52fe\u9009\u8be5dp\uff0c\u5219\u65e0\u4e00\u6b21\u6027\u5bc6\u7801\u529f\u80fd\u3002",
              "extensions": {
                "attribute": "128"
              },
              "name": "\u4e00\u6b21\u6027\u5bc6\u7801",
              "typeSpec": {}
            },
            {
              "abilityId": 76,
              "accessMode": "rw",
              "code": "normal_open_switch",
              "description": "\u8be5dp\u4e3a\u95e8\u9501\u5e38\u5f00\u529f\u80fd\uff0c\u6709\u8be5dp\u5219\u663e\u793a\u5e38\u5f00\u5f00\u5173\uff0c\u4e14\u652f\u6301\u5e38\u5f00\u8054\u52a8\u3002",
              "extensions": {
                "attribute": "256",
                "trigger": "direct"
              },
              "name": "\u5e38\u5f00\u5f00\u5173",
              "typeSpec": {}
            }
          ]
        }
      ]
    }
  }
}
````

**Comment by azerty9971** [comment]
Hello,
Can you try with the beta I just published right now?
v4.1.2-beta.2

Thanks in advance,
Azerty

**Comment by yurividal** [comment]
> Hello, Can you try with the beta I just published right now? v4.1.2-beta.2
> 
> Thanks in advance, Azerty

I'm trying, but i'm not sure i'm doing this right..
I have selected to redownload version 4.1.2-beta.2

<img width="1212" height="554" alt="Image" src="https://github.com/user-attachments/assets/be4d148b-004b-4a13-8df6-acd0076e4a1b" />

Then, i restarted HA.

But when i go to devices and services, and i click Xtend Tuya, it still shows 4.1.1

<img width="1023" height="284" alt="Image" src="https://github.com/user-attachments/assets/35741418-1f19-48b2-96e1-32d4898977ac" />

And the lock still shows unavailable action:

<img width="860" height="381" alt="Image" src="https://github.com/user-attachments/assets/e38a2d96-c142-4426-a130-363e33bdb0c2" />

**Comment by yurividal** [comment]
<img width="934" height="856" alt="Image" src="https://github.com/user-attachments/assets/b5c3a6fe-18ed-46d8-93c9-5778a35019b3" />

**Comment by anhhthnhy** [comment]
@azerty9971 I have a similar issue that hasn't been resolved yet
https://github.com/azerty9971/xtend_tuya/issues/391

**Comment by azerty9971** [comment]
Hello,
Can you update to 4.1.3-beta.1 and retry please?

Have a nice day,
Azerty

**Comment by yurividal** [comment]
> Hello, Can you update to 4.1.3-beta.1 and retry please?
> 
> Have a nice day, Azerty

4.1.3 seems to have fixed it!
