### ISSUE TITLE
All main entities gone after updating to v4.1.2

### ISSUE THREAD

**Issue by antonio1475** [azerty9971/xtend_tuya#447]
Hi,

After updating to [v4.1.2](https://github.com/azerty9971/xtend_tuya/tree/v4.1.2), all devices' main entities say
`This entity is no longer being provided by the xtend_tuya integration. If the entity is no longer in use, delete it in settings.`
<img width="1158" height="362" alt="Image" src="https://github.com/user-attachments/assets/716a1cf7-c283-4640-bd73-0dc57b34173a" />

No errors are shown, not I see anything in the logs.

The integration is indeed working, because sensors are working (through the cloud and not locally, because my HA server is in another country).

<img width="2132" height="1710" alt="Image" src="https://github.com/user-attachments/assets/d3318459-3452-45fa-859c-ca6883905c1a" />

I've already redownloaded the integration, tried to re-configure the credentials, and also gone through the Cloud Stream setting after updating (and multiple restarts) 🙏 

<img width="2126" height="1312" alt="Image" src="https://github.com/user-attachments/assets/1bd2bf2b-6c59-48e9-8348-85a090141e44" />

**Diagnostics:** 

[config_entry-xtend_tuya-01JSRGVYWFSHFKFMWGSSWTSKAP (2).json](https://github.com/user-attachments/files/21522032/config_entry-xtend_tuya-01JSRGVYWFSHFKFMWGSSWTSKAP.2.json)

**Comment by antonio1475** [comment]
Rollback to 4.1.1 fixed it...

**Comment by reaper7** [comment]
**v4.1.2-beta.1** and **v4.1.2-beta.2** works properly too, but final v4.1.2 not

**Comment by azerty9971** [comment]
Really sorry about this :'(.
The changes between beta2 and the release are really minimal, I don't know what happened :'(.

Do you have something in your system log in the release? there must be as per what you described...

Again, sorry about this,
Azerty

**Comment by antonio1475** [comment]
> Really sorry about this :'(. The changes between beta2 and the release are really minimal, I don't know what happened :'(.
> 
> Do you have something in your system log in the release? there must be as per what you described...
> 
> Again, sorry about this, Azerty

No worries, just glad that a simple rollback worked 😅
There was nothing in System > Logs linked to xtend_tuya or tuya, and I didn't download the full logs so now they seem to be lost after restart and cannot download 4.1.2 again to test and provide logs, can I? 😅

**Comment by rtlusciak** [comment]
Im sorry for the stupid qiestion...but how to  rollback? I need to restore all HA from backup?

**Comment by nrsobral73** [comment]
Hi,
I have the same problem and the rollback also solved it.
I've updated again to post anything that may be usefull.
The system log don't show anything.
I've downloaded the diagnostic from the device in the print screen.
I've got more devices with the same issue.  Water leakage like the one I've sent the log, door opened and an old light.
All these devices are wifi.
If I can help by sending more logs, just ask.
And many thanks for your work!

Regards

Nuno


<img width="1472" height="875" alt="Image" src="https://github.com/user-attachments/assets/723f30b0-0eda-4685-a7e1-990eb073e10f" />

[xtend_tuya-01JYBR9BC2M6VKZV3XAP8JJXRB-Sensor Agua Quarto-e556e1648b86db2688f7b184aaa989da.json](https://github.com/user-attachments/files/21527284/xtend_tuya-01JYBR9BC2M6VKZV3XAP8JJXRB-Sensor.Agua.Quarto-e556e1648b86db2688f7b184aaa989da.json)



[home-assistant_2025-07-31T09-26-32.971Z.log](https://github.com/user-attachments/files/21527192/home-assistant_2025-07-31T09-26-32.971Z.log)

**Comment by antonio1475** [comment]
> Im sorry for the stupid qiestion...but how to rollback? I need to restore all HA from backup?

HACS > Xtend Tuya > 3 dots (top-right) > Redownload > expand the `Need a different version?` > Choose the version that was working for you (4.1.1 or the betas) > Download > Restart

It says `It is not advised to use this section to do a rollback, restore a backup instead.` but in this case, it works.

**Comment by azerty9971** [comment]
> > Really sorry about this :'(. The changes between beta2 and the release are really minimal, I don't know what happened :'(.
> > Do you have something in your system log in the release? there must be as per what you described...
> > Again, sorry about this, Azerty
> 
> No worries, just glad that a simple rollback worked 😅 There was nothing in System > Logs linked to xtend_tuya or tuya, and I didn't download the full logs so now they seem to be lost after restart and cannot download 4.1.2 again to test and provide logs, can I? 😅

Indeed you can't, I've removed that release to prevent other users from having this issue :).

I can actually diagnose this on my prod system (it was all working fine on my dev but I'll replicate the same config and should get the same result...)

Once it's fixed I'll republish a release.

Again, sorry for the inconvenience, I try really hard for things like this not to happen but this one got through the net :/.

Have a nice day,
Azerty

**Comment by reaper7** [comment]
You're doing a great job! This is one of the best add-on, regularly developed.

Only those who do nothing make no mistakes :)

**Comment by nrsobral73** [comment]
> You're doing a great job! This is one of the best add-on, regularly developed.
> 
> Only those who do nothing make no mistakes :)

My words exactly!
No need to apologize, you do an amazing work, and we all benefit from it.

**Comment by reaper7** [comment]
Maybe this information will help you:

In my case, all of the TUYA devices are in a remote location (not on my local network). 
Additionally, my TUYA account doesn't own them; I'm added as an administrator to "home" by their owner. 
The devices were added through the owner's account, not my account. 

However, this worked very well in previous versions.

**Comment by azerty9971** [comment]
Hello,
Can you update to 4.1.3-beta.1 and retry please?

Have a nice day,
Azerty

**Comment by dziban303** [comment]
Hey,

i was having this problem too. updating to 4.1.3 beta2 fixed it. ( i didn't try the beta1 version). thank you!

**Comment by nrsobral73** [comment]
On 4.1.3 Beta 3 everything is working.
Thank you!!

**Comment by antonio1475** [comment]
All good here too, thank you! I'll leave it to you to close this issue or when a stable update is released? 😄

**Comment by reaper7** [comment]
4.1.3 Beta 3 works very well for me

**Comment by antonio1475** [comment]
@azerty9971 it's not exactly this but the current betas "break" the invert controls for covers. I wasn't sure if opening an issue for a beta is the way to go 😓 

4.1.1:

<img width="3420" height="1964" alt="Image" src="https://github.com/user-attachments/assets/10cb03ca-1b93-4fc4-a880-d44a0bfad7c2" />

4.1.3-beta.3:

<img width="3420" height="1964" alt="Image" src="https://github.com/user-attachments/assets/1047bb55-ff66-428e-a978-05e85694b7a7" />

**Comment by dziban303** [comment]
Some of my devices are back to saying the switch entity is not available
again. only affects some of my outlets

edit: deleted the outlets in smart life app, readded them, now they work.

**Comment by azerty9971** [comment]
Hello,
4.1.4 has just been published, this one should fix the issue :).

Can you try and let me know?

Thanks in advance,
Azerty

**Comment by nrsobral73** [comment]
Hi,
Everything is working fine on my end.
No issues.
Many thanks again for all your work.

**Comment by antonio1475** [comment]
All related to this issue and cover invert look good with 4.1.4
Thank you @azerty9971 👏 ❤️

**Comment by MrCanan** [comment]
Hi,

First, good job for your awesome work =)

Second, I also have the same issue as the first message about "Temperature and Humidity Sensor Wifi with screen"
> I still see it in the device tab of eu.platform.tuya.com/cloud
> All other Tuya in your "Extended Tuya integration for Home Assistant" works

I already tried to update, reload, restart, etc. But still the same problem
> I have had this issue since an update, perhaps the same as other people, so the 4.1.1, but I do not see it immediately, so I can not confirm it

Hope you will be able to solve it,
Best regards


<img width="750" height="472" alt="Image" src="https://github.com/user-attachments/assets/84d281e7-68dd-4910-9b62-8ed6638fa4a8" />
